// payroll_periods_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Payroll Profile picker ───────────────────────────────────────────────
  const payrollProfilePicker = $('#ppdPayrollProfilePickerTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/salary_setup/payroll_profiles/payroll_profiles_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#ppdPayrollProfilePickerTable tbody').on('click', 'tr', function () {
    const data = payrollProfilePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('ppdPayrollProfilePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ppd-payroll-profile-selected', { detail: data }));
  });

  $('#ppdPayrollProfilePickerModal').on('shown.bs.modal', function () {
    payrollProfilePicker.ajax.reload(null, false);
    payrollProfilePicker.columns.adjust();
  });

  const table = $('#payrollPeriodsSearchTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_payroll_profiles.name', defaultContent: '' },
      { data: 'code' },
      { data: 'name' },
      { data: 'start_date' },
      { data: 'end_date' },
      { data: 'payment_date' },
      { data: 'period_status' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Payroll Periods records',
    },
  });

  $('#payrollPeriodsSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('payrollPeriodsSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('payroll_periods-selected', { detail: data }));
  });

  $('#payrollPeriodsSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});