// payroll_periods.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      payroll_profile_ref: '',
      payroll_profile_name: '',
      code: '',
      name: '',
      start_date: '',
      end_date: '',
      payment_date: '',
      period_status: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.payroll_profile_ref !== '' ||
        this.form.code !== '' ||
        this.form.name !== '' ||
        this.form.start_date !== '' ||
        this.form.end_date !== '' ||
        this.form.payment_date !== '' ||
        this.form.period_status !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('payroll_periods-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('ppd-payroll-profile-selected', (e) => {
      this.form.payroll_profile_ref  = e.detail.ref;
      this.form.payroll_profile_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearPayrollProfile() { this.form.payroll_profile_ref = ''; this.form.payroll_profile_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        payroll_profile_name: String(this.form.payroll_profile_name ?? ''),
        code: String(this.form.code ?? ''),
        name: String(this.form.name ?? ''),
        start_date: String(this.form.start_date ?? ''),
        end_date: String(this.form.end_date ?? ''),
        payment_date: String(this.form.payment_date ?? ''),
        period_status: String(this.form.period_status ?? ''),
          });
          window.open('/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.payroll_profile_ref = '';
      this.form.payroll_profile_name = '';
      this.form.code = '';
      this.form.name = '';
      this.form.start_date = '';
      this.form.end_date = '';
      this.form.payment_date = '';
      this.form.period_status = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.payroll_profile_ref = data.payroll_profile_ref ?? '';
      this.form.payroll_profile_name = data.m_payroll_profiles?.name ?? '';
      this.form.code = data.code;
      this.form.name = data.name;
      this.form.start_date = data.start_date;
      this.form.end_date = data.end_date;
      this.form.payment_date = data.payment_date;
      this.form.period_status = data.period_status;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#payroll-periods-app');