<?php /* modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods.php — generated by Generate Module */ ?>

<div id="payroll-periods-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#payrollPeriodsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="payroll-periods-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="payroll-periods-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Payroll Profile</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="payroll-periods-payroll-profile-ref" v-model="form.payroll_profile_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.payroll_profile_name" placeholder="Payroll profile…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#ppdPayrollProfilePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearPayrollProfile" v-if="form.payroll_profile_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-periods-code" class="col-sm-4 col-form-label">Code</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="payroll-periods-code" v-model="form.code" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-periods-name" class="col-sm-4 col-form-label">Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="payroll-periods-name" v-model="form.name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-periods-start-date" class="col-sm-4 col-form-label">Start Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="payroll-periods-start-date" v-model="form.start_date" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-periods-end-date" class="col-sm-4 col-form-label">End Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="payroll-periods-end-date" v-model="form.end_date" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-periods-payment-date" class="col-sm-4 col-form-label">Payment Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="payroll-periods-payment-date" v-model="form.payment_date" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-periods-period-status" class="col-sm-4 col-form-label">Period Status</label>
      <div class="col-sm-8">
        <select class="form-select" id="payroll-periods-period-status" v-model="form.period_status" required>
                  <option value="" disabled>Select…</option>
                  <option value="Open">Open</option>
                  <option value="Processing">Processing</option>
                  <option value="Closed">Closed</option>
                </select>
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Payroll Periods saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/payroll_periods_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods.js"></script>