<?php
// designations_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveDesignations(array $data): array {
    $code = trim($data['code'] ?? '');
    $existing = supabase_get(SB_API . 'm_designations?select=id&code=eq.' . urlencode($code) . '&limit=1');
    if (!empty($existing)) {
        http_response_code(409);
        return ['error' => "Code '{$code}' already exists."];
    }

    $ref = consumeNextReference('designations');

    return supabase_post(SB_API . 'm_designations', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateDesignations(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_designations', $ref)) {
        return ['error' => 'Record not found.'];
    }

    $code = trim($data['code'] ?? '');
    $dup = supabase_get(SB_API . 'm_designations?select=id&code=eq.' . urlencode($code) . '&ref=neq.' . urlencode($ref) . '&limit=1');
    if (!empty($dup)) {
        http_response_code(409);
        return ['error' => "Code '{$code}' already exists."];
    }

    return supabase_patch(SB_API . 'm_designations?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listDesignations(): array {
    return supabase_get(SB_API . 'm_designations?select=id,ref,code,name,description&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listDesignations());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveDesignations($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateDesignations($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_designations', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}