// quotations_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Customer picker ──────────────────────────────────────────────────────
  const customerPicker = $('#qtCustomerPickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/customer_master_file/customer_master_file_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code', defaultContent: '' },
      { data: 'customer_name' },
      { data: 'phone', defaultContent: '' },
      { data: 'city', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#qtCustomerPickerTable tbody').on('click', 'tr', function () {
    const data = customerPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('qtCustomerPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('qt-customer-selected', { detail: data }));
  });

  $('#qtCustomerPickerModal').on('shown.bs.modal', function () {
    customerPicker.ajax.reload(null, false);
    customerPicker.columns.adjust();
  });

  // ── Quotation Status picker ──────────────────────────────────────────────
  const statusPicker = $('#qtStatusPickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/quotation_statuses/quotation_statuses_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#qtStatusPickerTable tbody').on('click', 'tr', function () {
    const data = statusPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('qtStatusPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('qt-status-selected', { detail: data }));
  });

  $('#qtStatusPickerModal').on('shown.bs.modal', function () {
    statusPicker.ajax.reload(null, false);
    statusPicker.columns.adjust();
  });

  // ── Currency picker ──────────────────────────────────────────────────────
  const currencyPicker = $('#qtCurrencyPickerTable').DataTable({
    ajax: { url: '/modules/finance/assets_budgeting/multi_currency/multi_currency_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'currency_code' },
      { data: 'currency_name' },
      { data: 'symbol', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#qtCurrencyPickerTable tbody').on('click', 'tr', function () {
    const data = currencyPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('qtCurrencyPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('qt-currency-selected', { detail: data }));
  });

  $('#qtCurrencyPickerModal').on('shown.bs.modal', function () {
    currencyPicker.ajax.reload(null, false);
    currencyPicker.columns.adjust();
  });

  // ── Salesperson picker ───────────────────────────────────────────────────
  const salespersonPicker = $('#qtSalespersonPickerTable').DataTable({
    ajax: { url: '/modules/master_files/people/employee_master/employee_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code', defaultContent: '' },
      { data: 'full_name' },
      { data: 'phone', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#qtSalespersonPickerTable tbody').on('click', 'tr', function () {
    const data = salespersonPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('qtSalespersonPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('qt-salesperson-selected', { detail: data }));
  });

  $('#qtSalespersonPickerModal').on('shown.bs.modal', function () {
    salespersonPicker.ajax.reload(null, false);
    salespersonPicker.columns.adjust();
  });

  const table = $('#quotationsSearchTable').DataTable({
    ajax: { url: '/modules/operations/quotations/quotation_entries/quotation_entries_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'revision_no', defaultContent: '0' },
      { data: 'm_customers.customer_name', defaultContent: '' },
      { data: 'subject', defaultContent: '' },
      { data: 'm_quotation_statuses.name', defaultContent: '' },
      { data: 'quotation_date' },
      { data: 'valid_until' },
      { data: 'total_amount' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Quotations records',
    },
  });

  $('#quotationsSearchTable tbody').on('click', 'tr', function () {
    const row = table.row(this).data();
    if (!row) return;
    axios.get('/modules/operations/quotations/quotation_entries/quotation_entries_data.php?action=get&ref=' + encodeURIComponent(row.ref))
      .then(res => {
        bootstrap.Modal.getInstance(document.getElementById('quotationsSearchModal')).hide();
        document.dispatchEvent(new CustomEvent('quotations-selected', { detail: res.data }));
      });
  });

  $('#quotationsSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});
