<?php /* modules/master_files/references/supplier_master/supplier_master.php — generated by Generate Module */ ?>

<div id="supplier-master-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#supplierMasterSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="supplier-master-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="supplier-master-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <form ref="form">
    <div class="row mb-3">
      <label for="supplier-master-supplier-name" class="col-sm-4 col-form-label">Supplier Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="supplier-master-supplier-name" v-model="form.supplier_name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="supplier-master-contact-person" class="col-sm-4 col-form-label">Contact Person</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="supplier-master-contact-person" v-model="form.contact_person" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="supplier-master-phone" class="col-sm-4 col-form-label">Phone</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="supplier-master-phone" v-model="form.phone" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="supplier-master-email" class="col-sm-4 col-form-label">Email</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="supplier-master-email" v-model="form.email" />
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Supplier Category</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="supplier-master-supplier-category-ref" v-model="form.supplier_category_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.supplier_category_name" placeholder="Supplier category…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#smSupplierCategoryPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearSupplierCategory" v-if="form.supplier_category_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="supplier-master-rate-card" class="col-sm-4 col-form-label">Rate Card</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="supplier-master-rate-card" v-model="form.rate_card"></textarea>
      </div>
    </div>
    </form>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Supplier Master saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/supplier_master_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/references/supplier_master/supplier_master.js"></script>