// supplier_master.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      supplier_name: '',
      contact_person: '',
      phone: '',
      email: '',
      supplier_category_ref: '',
      supplier_category_name: '',
      rate_card: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.supplier_name !== '' ||
        this.form.contact_person !== '' ||
        this.form.phone !== '' ||
        this.form.email !== '' ||
        this.form.supplier_category_ref !== '' ||
        this.form.rate_card !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('supplier_master-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('sm-supplier-category-selected', (e) => {
      this.form.supplier_category_ref  = e.detail.ref;
      this.form.supplier_category_name = e.detail.supplier_category_name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearSupplierCategory() { this.form.supplier_category_ref = ''; this.form.supplier_category_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/references/supplier_master/supplier_master_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        supplier_name: String(this.form.supplier_name ?? ''),
        contact_person: String(this.form.contact_person ?? ''),
        phone: String(this.form.phone ?? ''),
        email: String(this.form.email ?? ''),
        supplier_category_ref: String(this.form.supplier_category_ref ?? ''),
        supplier_category_name: String(this.form.supplier_category_name ?? ''),
        rate_card: String(this.form.rate_card ?? ''),
          });
          window.open('/modules/master_files/references/supplier_master/supplier_master_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.supplier_name = '';
      this.form.contact_person = '';
      this.form.phone = '';
      this.form.email = '';
      this.form.supplier_category_ref = '';
      this.form.supplier_category_name = '';
      this.form.rate_card = '';
    },

    onSave() {
      if (!this.isDirty) return;
      if (this.$refs.form && !this.$refs.form.reportValidity()) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/references/supplier_master/supplier_master_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = err.response?.data?.error || 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/references/supplier_master/supplier_master_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.supplier_name = data.supplier_name;
      this.form.contact_person = data.contact_person;
      this.form.phone = data.phone;
      this.form.email = data.email;
      this.form.supplier_category_ref = data.supplier_category_ref ?? '';
      this.form.supplier_category_name = data.m_supplier_categories?.supplier_category_name ?? '';
      this.form.rate_card = data.rate_card;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#supplier-master-app');