<?php
// event_type_master_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveEventTypeMaster(array $data): array {
    $ref = consumeNextReference('event_type_master');

    $record = supabase_post(SB_API . 'm_event_types', [
        'ref' => $ref,
        'event_type_name' => $data['event_type_name'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateEventTypeMaster(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_event_types', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_event_types?ref=eq.' . urlencode($ref), [
        'event_type_name' => $data['event_type_name'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listEventTypeMaster(): array {
    return supabase_get(SB_API . 'm_event_types?select=id,ref,event_type_name&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listEventTypeMaster());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveEventTypeMaster($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateEventTypeMaster($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_event_types', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}