<?php
// quotation_statuses_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveQuotationStatuses(array $data): array {
    $ref = consumeNextReference('quotation_statuses');

    return supabase_post(SB_API . 'm_quotation_statuses', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'sort_order' => $data['sort_order'] ?? 0,
        'is_default_status' => $data['is_default_status'] ?? false,
        'is_final_status' => $data['is_final_status'] ?? false,
        'can_create_work_order' => $data['can_create_work_order'] ?? false,
        'display_color' => $data['display_color'] ?? null,
        'icon' => $data['icon'] ?? null,
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateQuotationStatuses(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_quotation_statuses', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_quotation_statuses?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'sort_order' => $data['sort_order'] ?? 0,
        'is_default_status' => $data['is_default_status'] ?? false,
        'is_final_status' => $data['is_final_status'] ?? false,
        'can_create_work_order' => $data['can_create_work_order'] ?? false,
        'display_color' => $data['display_color'] ?? null,
        'icon' => $data['icon'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listQuotationStatuses(): array {
    return supabase_get(SB_API . 'm_quotation_statuses?select=id,ref,code,name,description,sort_order,is_default_status,is_final_status,can_create_work_order,display_color,icon&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listQuotationStatuses());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveQuotationStatuses($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateQuotationStatuses($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_quotation_statuses', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}