<?php
// supplier_category_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveSupplierCategory(array $data): array {
    $ref = consumeNextReference('supplier_category');

    $record = supabase_post(SB_API . 'm_supplier_categories', [
        'ref' => $ref,
        'supplier_category_name' => $data['supplier_category_name'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateSupplierCategory(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_supplier_categories', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_supplier_categories?ref=eq.' . urlencode($ref), [
        'supplier_category_name' => $data['supplier_category_name'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listSupplierCategory(): array {
    return supabase_get(SB_API . 'm_supplier_categories?select=id,ref,supplier_category_name&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listSupplierCategory());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveSupplierCategory($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateSupplierCategory($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_supplier_categories', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}