// supplier_category_search.js — generated by Generate Module

$(document).ready(function () {

  const table = $('#supplierCategorySearchTable').DataTable({
    ajax: { url: '/modules/master_files/references/supplier_category/supplier_category_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'supplier_category_name' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Supplier Category records',
    },
  });

  $('#supplierCategorySearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('supplierCategorySearchModal')).hide();
    document.dispatchEvent(new CustomEvent('supplier_category-selected', { detail: data }));
  });
  $('#supplierCategorySearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});