<?php /* modules/human_resources_payroll/salary_setup/salary_components/salary_components.php — generated by Generate Module */ ?>

<div id="salary-components-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#salaryComponentsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="salary-components-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="salary-components-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <form ref="form">
    <div class="row mb-3">
      <label for="salary-components-code" class="col-sm-4 col-form-label">Code</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="salary-components-code" v-model="form.code" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-components-name" class="col-sm-4 col-form-label">Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="salary-components-name" v-model="form.name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-components-description" class="col-sm-4 col-form-label">Description</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="salary-components-description" v-model="form.description"></textarea>
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-components-component-type" class="col-sm-4 col-form-label">Component Type</label>
      <div class="col-sm-8">
        <select class="form-select" id="salary-components-component-type" v-model="form.component_type" required>
                  <option value="" disabled>Select…</option>
                  <option value="Earning">Earning</option>
                  <option value="Deduction">Deduction</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-components-calculation-type" class="col-sm-4 col-form-label">Calculation Type</label>
      <div class="col-sm-8">
        <select class="form-select" id="salary-components-calculation-type" v-model="form.calculation_type" required>
                  <option value="" disabled>Select…</option>
                  <option value="Fixed Amount">Fixed Amount</option>
                  <option value="Percentage">Percentage</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-sm-8 offset-sm-4">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="salary-components-is-taxable" v-model="form.is_taxable" />
          <label class="form-check-label" for="salary-components-is-taxable">Is Taxable</label>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-sm-8 offset-sm-4">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="salary-components-is-recurring" v-model="form.is_recurring" />
          <label class="form-check-label" for="salary-components-is-recurring">Is Recurring</label>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-sm-8 offset-sm-4">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="salary-components-affects-gross-salary" v-model="form.affects_gross_salary" />
          <label class="form-check-label" for="salary-components-affects-gross-salary">Affects Gross Salary</label>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-sm-8 offset-sm-4">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="salary-components-affects-net-salary" v-model="form.affects_net_salary" />
          <label class="form-check-label" for="salary-components-affects-net-salary">Affects Net Salary</label>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-components-sort-order" class="col-sm-4 col-form-label">Sort Order</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="salary-components-sort-order" v-model.number="form.sort_order" />
      </div>
    </div>
    </form>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Salary Components saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/salary_components_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/human_resources_payroll/salary_setup/salary_components/salary_components.js"></script>