<?php
// salary_components_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveSalaryComponents(array $data): array {
    $code = trim($data['code'] ?? '');
    $existing = supabase_get(SB_API . 'm_salary_components?select=id&code=eq.' . urlencode($code) . '&limit=1');
    if (!empty($existing)) {
        http_response_code(409);
        return ['error' => "Code '{$code}' already exists."];
    }

    $ref = consumeNextReference('salary_components');

    return supabase_post(SB_API . 'm_salary_components', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'component_type' => $data['component_type'] ?? '',
        'calculation_type' => $data['calculation_type'] ?? '',
        'is_taxable' => $data['is_taxable'] ?? false,
        'is_recurring' => $data['is_recurring'] ?? false,
        'affects_gross_salary' => $data['affects_gross_salary'] ?? false,
        'affects_net_salary' => $data['affects_net_salary'] ?? false,
        'sort_order' => $data['sort_order'] ?? 0,
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateSalaryComponents(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_salary_components', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_salary_components?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'component_type' => $data['component_type'] ?? '',
        'calculation_type' => $data['calculation_type'] ?? '',
        'is_taxable' => $data['is_taxable'] ?? false,
        'is_recurring' => $data['is_recurring'] ?? false,
        'affects_gross_salary' => $data['affects_gross_salary'] ?? false,
        'affects_net_salary' => $data['affects_net_salary'] ?? false,
        'sort_order' => $data['sort_order'] ?? 0,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listSalaryComponents(): array {
    return supabase_get(SB_API . 'm_salary_components?select=id,ref,code,name,description,component_type,calculation_type,is_taxable,is_recurring,affects_gross_salary,affects_net_salary,sort_order&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listSalaryComponents());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveSalaryComponents($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateSalaryComponents($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_salary_components', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}