<?php
// quotation_terms_and_conditions_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveQuotationTermsAndConditions(array $data): array {
    $ref = consumeNextReference('quotation_terms_and_conditions');

    $record = supabase_post(SB_API . 'm_quotation_terms_conditions', [
        'ref' => $ref,
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateQuotationTermsAndConditions(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_quotation_terms_conditions', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_quotation_terms_conditions?ref=eq.' . urlencode($ref), [
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listQuotationTermsAndConditions(): array {
    return supabase_get(SB_API . 'm_quotation_terms_conditions?select=id,ref,name,description&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listQuotationTermsAndConditions());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveQuotationTermsAndConditions($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateQuotationTermsAndConditions($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_quotation_terms_conditions', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}