// employee_assignment_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Employment Record picker ─────────────────────────────────────────────
  const employmentRecordPicker = $('#eaEmploymentRecordPickerTable').DataTable({
    ajax: { url: '/modules/master_files/people/employment_record/employment_record_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_employees.full_name', defaultContent: '' },
      { data: 'm_employment_types.name', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#eaEmploymentRecordPickerTable tbody').on('click', 'tr', function () {
    const data = employmentRecordPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('eaEmploymentRecordPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ea-employment-record-selected', { detail: data }));
  });

  $('#eaEmploymentRecordPickerModal').on('shown.bs.modal', function () {
    employmentRecordPicker.ajax.reload(null, false);
    employmentRecordPicker.columns.adjust();
  });

  // ── Department picker ────────────────────────────────────────────────────
  const departmentPicker = $('#eaDepartmentPickerTable').DataTable({
    ajax: { url: '/modules/master_files/organisation/department/department_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#eaDepartmentPickerTable tbody').on('click', 'tr', function () {
    const data = departmentPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('eaDepartmentPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ea-department-selected', { detail: data }));
  });

  $('#eaDepartmentPickerModal').on('shown.bs.modal', function () {
    departmentPicker.ajax.reload(null, false);
    departmentPicker.columns.adjust();
  });

  // ── Designation picker ───────────────────────────────────────────────────
  const designationPicker = $('#eaDesignationPickerTable').DataTable({
    ajax: { url: '/modules/master_files/organisation/designations/designations_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#eaDesignationPickerTable tbody').on('click', 'tr', function () {
    const data = designationPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('eaDesignationPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ea-designation-selected', { detail: data }));
  });

  $('#eaDesignationPickerModal').on('shown.bs.modal', function () {
    designationPicker.ajax.reload(null, false);
    designationPicker.columns.adjust();
  });

  const table = $('#employeeAssignmentSearchTable').DataTable({
    ajax: { url: '/modules/master_files/people/employee_assignment/employee_assignment_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_employment_records.m_employees.full_name', defaultContent: '' },
      { data: 'm_departments.name', defaultContent: '' },
      { data: 'm_designations.name', defaultContent: '' },
      { data: 'effective_from' },
      { data: 'effective_to' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Employee Assignment records',
    },
  });

  $('#employeeAssignmentSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('employeeAssignmentSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('employee_assignment-selected', { detail: data }));
  });

  $('#employeeAssignmentSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});