<?php /* modules/master_files/people/employee_assignment/employee_assignment.php — generated by Generate Module */ ?>

<div id="employee-assignment-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#employeeAssignmentSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="employee-assignment-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="employee-assignment-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Employment Record</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="employee-assignment-employment-record-ref" v-model="form.employment_record_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.employment_record_name" placeholder="Employment record…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#eaEmploymentRecordPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearEmploymentRecord" v-if="form.employment_record_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Department</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="employee-assignment-department-ref" v-model="form.department_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.department_name" placeholder="Department…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#eaDepartmentPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearDepartment" v-if="form.department_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Designation</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="employee-assignment-designation-ref" v-model="form.designation_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.designation_name" placeholder="Designation…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#eaDesignationPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearDesignation" v-if="form.designation_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="employee-assignment-effective-from" class="col-sm-4 col-form-label">Effective From</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="employee-assignment-effective-from" v-model="form.effective_from" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="employee-assignment-effective-to" class="col-sm-4 col-form-label">Effective To</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="employee-assignment-effective-to" v-model="form.effective_to" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="employee-assignment-remarks" class="col-sm-4 col-form-label">Remarks</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="employee-assignment-remarks" v-model="form.remarks"></textarea>
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Employee Assignment saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/employee_assignment_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/people/employee_assignment/employee_assignment.js"></script>