<?php
// employee_assignment_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveEmployeeAssignment(array $data): array {
    $ref = consumeNextReference('employee_assignment');

    return supabase_post(SB_API . 'm_employee_assignments', [
        'ref' => $ref,
        'employment_record_ref' => !empty($data['employment_record_ref']) ? $data['employment_record_ref'] : null,
        'department_ref' => !empty($data['department_ref']) ? $data['department_ref'] : null,
        'designation_ref' => !empty($data['designation_ref']) ? $data['designation_ref'] : null,
        'effective_from' => !empty($data['effective_from']) ? $data['effective_from'] : null,
        'effective_to' => !empty($data['effective_to']) ? $data['effective_to'] : null,
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateEmployeeAssignment(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_employee_assignments', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_employee_assignments?ref=eq.' . urlencode($ref), [
        'employment_record_ref' => !empty($data['employment_record_ref']) ? $data['employment_record_ref'] : null,
        'department_ref' => !empty($data['department_ref']) ? $data['department_ref'] : null,
        'designation_ref' => !empty($data['designation_ref']) ? $data['designation_ref'] : null,
        'effective_from' => !empty($data['effective_from']) ? $data['effective_from'] : null,
        'effective_to' => !empty($data['effective_to']) ? $data['effective_to'] : null,
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listEmployeeAssignment(): array {
    return supabase_get(SB_API . 'm_employee_assignments?select=id,ref,employment_record_ref,department_ref,designation_ref,effective_from,effective_to,remarks,m_employment_records(ref,m_employees(full_name)),m_departments(name),m_designations(name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listEmployeeAssignment());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveEmployeeAssignment($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateEmployeeAssignment($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_employee_assignments', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}