// employee_assignment.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      employment_record_ref: '',
      employment_record_name: '',
      department_ref: '',
      department_name: '',
      designation_ref: '',
      designation_name: '',
      effective_from: '',
      effective_to: '',
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.employment_record_ref !== '' ||
        this.form.department_ref !== '' ||
        this.form.designation_ref !== '' ||
        this.form.effective_from !== '' ||
        this.form.effective_to !== '' ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('employee_assignment-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('ea-employment-record-selected', (e) => {
      this.form.employment_record_ref  = e.detail.ref;
      this.form.employment_record_name = e.detail.m_employees?.full_name ?? e.detail.ref;
    });
    document.addEventListener('ea-department-selected', (e) => {
      this.form.department_ref  = e.detail.ref;
      this.form.department_name = e.detail.name;
    });
    document.addEventListener('ea-designation-selected', (e) => {
      this.form.designation_ref  = e.detail.ref;
      this.form.designation_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearEmploymentRecord() { this.form.employment_record_ref = ''; this.form.employment_record_name = ''; },
    clearDepartment()       { this.form.department_ref = '';        this.form.department_name = ''; },
    clearDesignation()      { this.form.designation_ref = '';       this.form.designation_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/people/employee_assignment/employee_assignment_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        employment_record_name: String(this.form.employment_record_name ?? ''),
        department_name: String(this.form.department_name ?? ''),
        designation_name: String(this.form.designation_name ?? ''),
        effective_from: String(this.form.effective_from ?? ''),
        effective_to: String(this.form.effective_to ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/master_files/people/employee_assignment/employee_assignment_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.employment_record_ref = '';
      this.form.employment_record_name = '';
      this.form.department_ref = '';
      this.form.department_name = '';
      this.form.designation_ref = '';
      this.form.designation_name = '';
      this.form.effective_from = '';
      this.form.effective_to = '';
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/people/employee_assignment/employee_assignment_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/people/employee_assignment/employee_assignment_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.employment_record_ref = data.employment_record_ref ?? '';
      this.form.employment_record_name = data.m_employment_records?.m_employees?.full_name ?? data.employment_record_ref ?? '';
      this.form.department_ref = data.department_ref ?? '';
      this.form.department_name = data.m_departments?.name ?? '';
      this.form.designation_ref = data.designation_ref ?? '';
      this.form.designation_name = data.m_designations?.name ?? '';
      this.form.effective_from = data.effective_from;
      this.form.effective_to = data.effective_to;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#employee-assignment-app');