<?php
// vehicle_maintenance_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveVehicleMaintenance(array $data): array {
    $ref = consumeNextReference('vehicle_maintenance');

    return supabase_post(SB_API . 't_vehicle_maintenance', [
        'ref' => $ref,
        'vehicle_ref' => !empty($data['vehicle_ref']) ? $data['vehicle_ref'] : null,
        'maintenance_type_ref' => !empty($data['maintenance_type_ref']) ? $data['maintenance_type_ref'] : null,
        'service_provider' => $data['service_provider'] ?? '',
        'scheduled_date' => !empty($data['scheduled_date']) ? $data['scheduled_date'] : null,
        'start_date' => !empty($data['start_date']) ? $data['start_date'] : null,
        'completed_date' => !empty($data['completed_date']) ? $data['completed_date'] : null,
        'odometer_km' => $data['odometer_km'] ?? 0,
        'labour_cost' => $data['labour_cost'] ?? 0,
        'parts_cost' => $data['parts_cost'] ?? 0,
        'total_cost' => $data['total_cost'] ?? 0,
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateVehicleMaintenance(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('t_vehicle_maintenance', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 't_vehicle_maintenance?ref=eq.' . urlencode($ref), [
        'vehicle_ref' => !empty($data['vehicle_ref']) ? $data['vehicle_ref'] : null,
        'maintenance_type_ref' => !empty($data['maintenance_type_ref']) ? $data['maintenance_type_ref'] : null,
        'service_provider' => $data['service_provider'] ?? '',
        'scheduled_date' => !empty($data['scheduled_date']) ? $data['scheduled_date'] : null,
        'start_date' => !empty($data['start_date']) ? $data['start_date'] : null,
        'completed_date' => !empty($data['completed_date']) ? $data['completed_date'] : null,
        'odometer_km' => $data['odometer_km'] ?? 0,
        'labour_cost' => $data['labour_cost'] ?? 0,
        'parts_cost' => $data['parts_cost'] ?? 0,
        'total_cost' => $data['total_cost'] ?? 0,
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listVehicleMaintenance(): array {
    return supabase_get(SB_API . 't_vehicle_maintenance?select=id,ref,vehicle_ref,maintenance_type_ref,service_provider,scheduled_date,start_date,completed_date,odometer_km,labour_cost,parts_cost,total_cost,remarks,m_vehicles(ref,plate_number),m_maintenance_types(name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listVehicleMaintenance());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveVehicleMaintenance($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateVehicleMaintenance($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('t_vehicle_maintenance', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}