// vehicle_maintenance.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      vehicle_ref: '',
      vehicle_plate: '',
      maintenance_type_ref: '',
      maintenance_type_name: '',
      service_provider: '',
      scheduled_date: '',
      start_date: '',
      completed_date: '',
      odometer_km: 0,
      labour_cost: 0,
      parts_cost: 0,
      total_cost: 0,
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.vehicle_ref !== '' ||
        this.form.maintenance_type_ref !== '' ||
        this.form.service_provider !== '' ||
        this.form.scheduled_date !== '' ||
        this.form.start_date !== '' ||
        this.form.completed_date !== '' ||
        this.form.odometer_km !== 0 ||
        this.form.labour_cost !== 0 ||
        this.form.parts_cost !== 0 ||
        this.form.total_cost !== 0 ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('vehicle_maintenance-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('vmt-vehicle-selected', (e) => {
      this.form.vehicle_ref   = e.detail.ref;
      this.form.vehicle_plate = e.detail.plate_number;
    });
    document.addEventListener('vmt-maintenance-type-selected', (e) => {
      this.form.maintenance_type_ref  = e.detail.ref;
      this.form.maintenance_type_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearVehicle()         { this.form.vehicle_ref = '';         this.form.vehicle_plate = ''; },
    clearMaintenanceType() { this.form.maintenance_type_ref = ''; this.form.maintenance_type_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/operations/fleet_maintenance/vehicle_maintenance/vehicle_maintenance_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        vehicle_plate: String(this.form.vehicle_plate ?? ''),
        maintenance_type_name: String(this.form.maintenance_type_name ?? ''),
        service_provider: String(this.form.service_provider ?? ''),
        scheduled_date: String(this.form.scheduled_date ?? ''),
        start_date: String(this.form.start_date ?? ''),
        completed_date: String(this.form.completed_date ?? ''),
        odometer_km: String(this.form.odometer_km ?? ''),
        labour_cost: String(this.form.labour_cost ?? ''),
        parts_cost: String(this.form.parts_cost ?? ''),
        total_cost: String(this.form.total_cost ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/operations/fleet_maintenance/vehicle_maintenance/vehicle_maintenance_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.vehicle_ref = '';
      this.form.vehicle_plate = '';
      this.form.maintenance_type_ref = '';
      this.form.maintenance_type_name = '';
      this.form.service_provider = '';
      this.form.scheduled_date = '';
      this.form.start_date = '';
      this.form.completed_date = '';
      this.form.odometer_km = 0;
      this.form.labour_cost = 0;
      this.form.parts_cost = 0;
      this.form.total_cost = 0;
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/operations/fleet_maintenance/vehicle_maintenance/vehicle_maintenance_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/operations/fleet_maintenance/vehicle_maintenance/vehicle_maintenance_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.vehicle_ref = data.vehicle_ref ?? '';
      this.form.vehicle_plate = data.m_vehicles?.plate_number ?? '';
      this.form.maintenance_type_ref = data.maintenance_type_ref ?? '';
      this.form.maintenance_type_name = data.m_maintenance_types?.name ?? '';
      this.form.service_provider = data.service_provider;
      this.form.scheduled_date = data.scheduled_date;
      this.form.start_date = data.start_date;
      this.form.completed_date = data.completed_date;
      this.form.odometer_km = data.odometer_km;
      this.form.labour_cost = data.labour_cost;
      this.form.parts_cost = data.parts_cost;
      this.form.total_cost = data.total_cost;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#vehicle-maintenance-app');