<?php /* modules/operations/fleet_maintenance/vehicle_maintenance/vehicle_maintenance_search.php — search modal; generated by Generate Module */ ?>

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.bootstrap5.min.css" crossorigin="anonymous" />

<!-- Vehicle picker modal -->
<div class="modal fade" id="vmtVehiclePickerModal" tabindex="-1" aria-labelledby="vmtVehiclePickerLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-fullscreen-sm-down">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="vmtVehiclePickerLabel">Select Vehicle</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
        <table id="vmtVehiclePickerTable" class="table table-bordered table-hover align-middle" style="width:100%;cursor:pointer">
          <thead class="table-light"><tr><th>Ref</th><th>Plate</th><th>Make</th><th>Model</th><th>Type</th><th>Status</th></tr></thead>
        </table>
        </div>
      </div>
      <div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button></div>
    </div>
  </div>
</div>

<!-- Maintenance Type picker modal -->
<div class="modal fade" id="vmtMaintenanceTypePickerModal" tabindex="-1" aria-labelledby="vmtMaintenanceTypePickerLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-fullscreen-sm-down">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="vmtMaintenanceTypePickerLabel">Select Maintenance Type</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
        <table id="vmtMaintenanceTypePickerTable" class="table table-bordered table-hover align-middle" style="width:100%;cursor:pointer">
          <thead class="table-light"><tr><th>Ref</th><th>Code</th><th>Name</th><th>Status</th></tr></thead>
        </table>
        </div>
      </div>
      <div class="modal-footer"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button></div>
    </div>
  </div>
</div>

<div class="modal fade" id="vehicleMaintenanceSearchModal" tabindex="-1" aria-labelledby="vehicleMaintenanceSearchModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-fullscreen-sm-down">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="vehicleMaintenanceSearchModalLabel">Vehicle Maintenance Search</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="table-responsive">
        <table id="vehicleMaintenanceSearchTable" class="table table-bordered table-striped table-hover align-middle" style="width:100%;cursor:pointer">
          <thead class="table-light">
            <tr>
              <th>Ref</th>
              <th>Vehicle</th>
              <th>Maintenance Type</th>
              <th>Service Provider</th>
              <th>Scheduled Date</th>
              <th>Start Date</th>
              <th>Completed Date</th>
              <th>Odometer (km)</th>
              <th>Labour Cost</th>
              <th>Parts Cost</th>
              <th>Total Cost</th>
              <th>Remarks</th>
            </tr>
          </thead>
        </table>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.7.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.bootstrap5.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js" crossorigin="anonymous"></script>
<script src="/modules/operations/fleet_maintenance/vehicle_maintenance/vehicle_maintenance_search.js"></script>