// quotation_statuses.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      code: '',
      name: '',
      description: '',
      sort_order: 0,
      is_default_status: false,
      is_final_status: false,
      can_create_work_order: false,
      display_color: '#6c757d',
      icon: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.code !== '' ||
        this.form.name !== '' ||
        this.form.description !== '' ||
        this.form.sort_order !== 0 ||
        this.form.is_default_status !== false ||
        this.form.is_final_status !== false ||
        this.form.can_create_work_order !== false ||
        this.form.icon !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('quotation_statuses-selected', (e) => this.loadRecord(e.detail));
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/references/quotation_statuses/quotation_statuses_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        code: String(this.form.code ?? ''),
        name: String(this.form.name ?? ''),
        description: String(this.form.description ?? ''),
        sort_order: String(this.form.sort_order ?? ''),
        is_default_status: String(this.form.is_default_status ?? ''),
        is_final_status: String(this.form.is_final_status ?? ''),
        can_create_work_order: String(this.form.can_create_work_order ?? ''),
        display_color: String(this.form.display_color ?? ''),
        icon: String(this.form.icon ?? ''),
          });
          window.open('/modules/master_files/references/quotation_statuses/quotation_statuses_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.code = '';
      this.form.name = '';
      this.form.description = '';
      this.form.sort_order = 0;
      this.form.is_default_status = false;
      this.form.is_final_status = false;
      this.form.can_create_work_order = false;
      this.form.display_color = '#6c757d';
      this.form.icon = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/references/quotation_statuses/quotation_statuses_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/references/quotation_statuses/quotation_statuses_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.code = data.code;
      this.form.name = data.name;
      this.form.description = data.description;
      this.form.sort_order = data.sort_order;
      this.form.is_default_status = data.is_default_status;
      this.form.is_final_status = data.is_final_status;
      this.form.can_create_work_order = data.can_create_work_order;
      this.form.display_color = data.display_color || '#6c757d';
      this.form.icon = data.icon ?? '';
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#quotation-statuses-app');