// work_orders_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Customer picker ──────────────────────────────────────────────────────
  const customerPicker = $('#woCustomerPickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/customer_master_file/customer_master_file_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code', defaultContent: '' },
      { data: 'customer_name' },
      { data: 'phone', defaultContent: '' },
      { data: 'city', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#woCustomerPickerTable tbody').on('click', 'tr', function () {
    const data = customerPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('woCustomerPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('wo-customer-selected', { detail: data }));
  });

  $('#woCustomerPickerModal').on('shown.bs.modal', function () {
    customerPicker.ajax.reload(null, false);
    customerPicker.columns.adjust();
  });

  // ── Work Order Type picker ───────────────────────────────────────────────
  const typePicker = $('#woTypePickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/work_order_types/work_order_types_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#woTypePickerTable tbody').on('click', 'tr', function () {
    const data = typePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('woTypePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('wo-type-selected', { detail: data }));
  });

  $('#woTypePickerModal').on('shown.bs.modal', function () {
    typePicker.ajax.reload(null, false);
    typePicker.columns.adjust();
  });

  // ── Quotation picker ─────────────────────────────────────────────────────
  const quotationPicker = $('#woQuotationPickerTable').DataTable({
    ajax: { url: '/modules/operations/quotations/quotation_entries/quotation_entries_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_customers.customer_name', defaultContent: '' },
      { data: 'quotation_date', defaultContent: '' },
      { data: 'total_amount', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#woQuotationPickerTable tbody').on('click', 'tr', function () {
    const data = quotationPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('woQuotationPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('wo-quotation-selected', { detail: data }));
  });

  $('#woQuotationPickerModal').on('shown.bs.modal', function () {
    quotationPicker.ajax.reload(null, false);
    quotationPicker.columns.adjust();
  });

  // ── Work Order Status picker ─────────────────────────────────────────────
  const statusPicker = $('#woStatusPickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/work_order_statuses/work_order_statuses_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#woStatusPickerTable tbody').on('click', 'tr', function () {
    const data = statusPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('woStatusPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('wo-status-selected', { detail: data }));
  });

  $('#woStatusPickerModal').on('shown.bs.modal', function () {
    statusPicker.ajax.reload(null, false);
    statusPicker.columns.adjust();
  });

  const table = $('#workOrdersSearchTable').DataTable({
    ajax: { url: '/modules/operations/work_orders/work_order_entries/work_order_entries_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_customers.customer_name', defaultContent: '' },
      { data: 'm_work_order_types.name', defaultContent: '' },
      { data: 'm_work_order_statuses.name', defaultContent: '' },
      { data: 'requested_date' },
      { data: 'planned_start' },
      { data: 'planned_end' },
      { data: 'actual_start' },
      { data: 'actual_end' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Work Orders records',
    },
  });

  $('#workOrdersSearchTable tbody').on('click', 'tr', function () {
    const row = table.row(this).data();
    if (!row) return;
    axios.get('/modules/operations/work_orders/work_order_entries/work_order_entries_data.php?action=get&ref=' + encodeURIComponent(row.ref))
      .then(res => {
        bootstrap.Modal.getInstance(document.getElementById('workOrdersSearchModal')).hide();
        document.dispatchEvent(new CustomEvent('work_orders-selected', { detail: res.data }));
      });
  });

  $('#workOrdersSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});
