// work_order_entries.js — generated by Generate Module

const { createApp } = Vue;

const emptyLine = () => ({
  pickup_location_ref: '',
  pickup_location_name: '',
  delivery_location_ref: '',
  delivery_location_name: '',
  vehicle_type_ref: '',
  vehicle_type_name: '',
  planned_start: '',
  planned_end: '',
  vehicle_ref: '',
  vehicle_plate: '',
  driver_ref: '',
  driver_name: '',
  remarks: '',
});

const lineHasData = (l) => (
  l.pickup_location_ref || l.delivery_location_ref || l.vehicle_type_ref ||
  l.vehicle_ref || l.driver_ref || l.remarks
);

// Standard master-file picker field: Ref + Name (both read-only) + search + clear,
// matching the header-level Customer/Type/Status pickers on this same screen.
const PickerField = {
  props: ['label', 'placeholder', 'refValue', 'nameValue'],
  emits: ['open', 'clear'],
  template: `
    <label class="form-label small text-muted mb-1">{{ label }}</label>
    <div class="input-group input-group-sm">
      <input type="text" class="form-control font-monospace" :value="refValue" placeholder="Ref…" readonly style="max-width:90px" />
      <input type="text" class="form-control" :value="nameValue" :placeholder="placeholder" readonly />
      <button class="btn btn-outline-primary" type="button" @click="$emit('open')" title="Pick">
        <i class="bi bi-search"></i>
      </button>
      <button class="btn btn-outline-secondary" type="button" @click="$emit('clear')" v-if="refValue">
        <i class="bi bi-x-lg"></i>
      </button>
    </div>
  `,
};

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      pickerLineIndex: null,
      pickerField: null,
      form: {
        ref: '',
      customer_ref: '',
      customer_name: '',
      work_order_type_ref: '',
      work_order_type_name: '',
      quotation_ref: '',
      work_order_status_ref: '',
      work_order_status_name: '',
      requested_date: '',
      planned_start: '',
      planned_end: '',
      actual_start: '',
      actual_end: '',
      description: '',
      remarks: '',
      lines: [emptyLine()],
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.customer_ref !== '' ||
        this.form.work_order_type_ref !== '' ||
        this.form.quotation_ref !== '' ||
        this.form.work_order_status_ref !== '' ||
        this.form.requested_date !== '' ||
        this.form.planned_start !== '' ||
        this.form.planned_end !== '' ||
        this.form.actual_start !== '' ||
        this.form.actual_end !== '' ||
        this.form.description !== '' ||
        this.form.remarks !== '' ||
        this.form.lines.some(lineHasData)
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('work_orders-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('wo-customer-selected', (e) => {
      this.form.customer_ref  = e.detail.ref;
      this.form.customer_name = e.detail.customer_name;
    });
    document.addEventListener('wo-type-selected', (e) => {
      this.form.work_order_type_ref  = e.detail.ref;
      this.form.work_order_type_name = e.detail.name;
    });
    document.addEventListener('wo-quotation-selected', (e) => {
      this.form.quotation_ref = e.detail.ref;
    });
    document.addEventListener('wo-status-selected', (e) => {
      this.form.work_order_status_ref  = e.detail.ref;
      this.form.work_order_status_name = e.detail.name;
    });

    document.addEventListener('wol-location-selected', (e) => {
      if (this.pickerLineIndex === null || !this.pickerField) return;
      const line = this.form.lines[this.pickerLineIndex];
      if (!line) return;
      if (this.pickerField === 'pickup_location') {
        line.pickup_location_ref  = e.detail.ref;
        line.pickup_location_name = e.detail.name;
      } else if (this.pickerField === 'delivery_location') {
        line.delivery_location_ref  = e.detail.ref;
        line.delivery_location_name = e.detail.name;
      }
      this.pickerLineIndex = null;
      this.pickerField = null;
    });
    document.addEventListener('wol-vehicle-type-selected', (e) => {
      if (this.pickerLineIndex === null) return;
      const line = this.form.lines[this.pickerLineIndex];
      if (!line) return;
      line.vehicle_type_ref  = e.detail.ref;
      line.vehicle_type_name = e.detail.name;
      this.pickerLineIndex = null;
    });
    document.addEventListener('wol-vehicle-selected', (e) => {
      if (this.pickerLineIndex === null) return;
      const line = this.form.lines[this.pickerLineIndex];
      if (!line) return;
      line.vehicle_ref   = e.detail.ref;
      line.vehicle_plate = e.detail.plate_number;
      this.pickerLineIndex = null;
    });
    document.addEventListener('wol-driver-selected', (e) => {
      if (this.pickerLineIndex === null) return;
      const line = this.form.lines[this.pickerLineIndex];
      if (!line) return;
      line.driver_ref  = e.detail.ref;
      line.driver_name = e.detail.name;
      this.pickerLineIndex = null;
    });
  },

  methods: {
    toDatetimeLocal(value) {
      return value ? String(value).slice(0, 16) : '';
    },

    dateTimePicker(value, onChange) {
      return { modelValue: value, onChange, options: { enableTime: true, dateFormat: 'Y-m-d H:i', altInput: true, altFormat: 'd M Y, h:i K', minuteIncrement: 15 } };
    },
    dateTimePickerCompact(value, onChange) {
      return { modelValue: value, onChange, options: { enableTime: true, dateFormat: 'Y-m-d H:i', altInput: true, altFormat: 'd/m/y H:i', minuteIncrement: 15 } };
    },

    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearCustomer()        { this.form.customer_ref = ''; this.form.customer_name = ''; },
    clearWorkOrderType()   { this.form.work_order_type_ref = ''; this.form.work_order_type_name = ''; },
    clearQuotation()       { this.form.quotation_ref = ''; },
    clearWorkOrderStatus() { this.form.work_order_status_ref = ''; this.form.work_order_status_name = ''; },

    clearLineField(i, refField, nameField) {
      this.form.lines[i][refField] = '';
      this.form.lines[i][nameField] = '';
    },

    addLine()     { this.form.lines.push(emptyLine()); },
    removeLine(i) { if (this.form.lines.length > 1) this.form.lines.splice(i, 1); },

    openPickupLocationPicker(i) {
      this.pickerLineIndex = i;
      this.pickerField = 'pickup_location';
      new bootstrap.Modal(document.getElementById('wolLocationPickerModal')).show();
    },
    openDeliveryLocationPicker(i) {
      this.pickerLineIndex = i;
      this.pickerField = 'delivery_location';
      new bootstrap.Modal(document.getElementById('wolLocationPickerModal')).show();
    },
    openVehicleTypePicker(i) {
      this.pickerLineIndex = i;
      new bootstrap.Modal(document.getElementById('wolVehicleTypePickerModal')).show();
    },
    openVehiclePicker(i) {
      this.pickerLineIndex = i;
      new bootstrap.Modal(document.getElementById('wolVehiclePickerModal')).show();
    },
    openDriverPicker(i) {
      this.pickerLineIndex = i;
      new bootstrap.Modal(document.getElementById('wolDriverPickerModal')).show();
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/operations/work_orders/work_order_entries/work_order_entries_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        customer_name: String(this.form.customer_name ?? ''),
        work_order_type_name: String(this.form.work_order_type_name ?? ''),
        quotation_ref: String(this.form.quotation_ref ?? ''),
        work_order_status_name: String(this.form.work_order_status_name ?? ''),
        requested_date: String(this.form.requested_date ?? ''),
        planned_start: String(this.form.planned_start ?? ''),
        planned_end: String(this.form.planned_end ?? ''),
        actual_start: String(this.form.actual_start ?? ''),
        actual_end: String(this.form.actual_end ?? ''),
        description: String(this.form.description ?? ''),
        remarks: String(this.form.remarks ?? ''),
        lines: JSON.stringify(this.form.lines.filter(lineHasData)),
          });
          window.open('/modules/operations/work_orders/work_order_entries/work_order_entries_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.customer_ref = '';
      this.form.customer_name = '';
      this.form.work_order_type_ref = '';
      this.form.work_order_type_name = '';
      this.form.quotation_ref = '';
      this.form.work_order_status_ref = '';
      this.form.work_order_status_name = '';
      this.form.requested_date = '';
      this.form.planned_start = '';
      this.form.planned_end = '';
      this.form.actual_start = '';
      this.form.actual_end = '';
      this.form.description = '';
      this.form.remarks = '';
      this.form.lines = [emptyLine()];
      this.pickerLineIndex = null;
      this.pickerField = null;
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';
      const payload = { ...this.form, lines: this.form.lines.filter(lineHasData) };

      const proceed = (action) => {
        axios.post('/modules/operations/work_orders/work_order_entries/work_order_entries_data.php?action=' + action, payload)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/operations/work_orders/work_order_entries/work_order_entries_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.customer_ref = data.customer_ref ?? '';
      this.form.customer_name = data.m_customers?.customer_name ?? '';
      this.form.work_order_type_ref = data.work_order_type_ref ?? '';
      this.form.work_order_type_name = data.m_work_order_types?.name ?? '';
      this.form.quotation_ref = data.quotation_ref ?? '';
      this.form.work_order_status_ref = data.work_order_status_ref ?? '';
      this.form.work_order_status_name = data.m_work_order_statuses?.name ?? '';
      this.form.requested_date = this.toDatetimeLocal(data.requested_date);
      this.form.planned_start = this.toDatetimeLocal(data.planned_start);
      this.form.planned_end = this.toDatetimeLocal(data.planned_end);
      this.form.actual_start = this.toDatetimeLocal(data.actual_start);
      this.form.actual_end = this.toDatetimeLocal(data.actual_end);
      this.form.description = data.description;
      this.form.remarks = data.remarks;
      this.form.lines = (data.lines && data.lines.length)
        ? data.lines.map(l => ({
            pickup_location_ref: l.pickup_location_ref ?? '',
            pickup_location_name: l.pickup_location_name ?? '',
            delivery_location_ref: l.delivery_location_ref ?? '',
            delivery_location_name: l.delivery_location_name ?? '',
            vehicle_type_ref: l.vehicle_type_ref ?? '',
            vehicle_type_name: l.m_vehicle_types?.name ?? '',
            planned_start: this.toDatetimeLocal(l.planned_start),
            planned_end: this.toDatetimeLocal(l.planned_end),
            vehicle_ref: l.vehicle_ref ?? '',
            vehicle_plate: l.vehicle_plate ?? '',
            driver_ref: l.driver_ref ?? '',
            driver_name: l.driver_name ?? '',
            remarks: l.remarks ?? '',
          }))
        : [emptyLine()];
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
})
  .component('picker-field', PickerField)
  .directive('flatpickr', window.FlatpickrDirective)
  .mount('#work-orders-app');
