// vehicle_documents.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      vehicle_ref: '',
      vehicle_plate: '',
      document_type_ref: '',
      document_type_name: '',
      document_number: '',
      issue_date: '',
      expiry_date: '',
      issued_by: '',
      attachment: '',
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.vehicle_ref !== '' ||
        this.form.document_type_ref !== '' ||
        this.form.document_number !== '' ||
        this.form.issue_date !== '' ||
        this.form.expiry_date !== '' ||
        this.form.issued_by !== '' ||
        this.form.attachment !== '' ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('vehicle_documents-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('vdc-vehicle-selected', (e) => {
      this.form.vehicle_ref   = e.detail.ref;
      this.form.vehicle_plate = e.detail.plate_number;
    });
    document.addEventListener('vdc-document-type-selected', (e) => {
      this.form.document_type_ref  = e.detail.ref;
      this.form.document_type_name = e.detail.name;
    });
  },

  methods: {
    datePicker(value, onChange) {
      return { modelValue: value, onChange, options: { dateFormat: 'Y-m-d', altInput: true, altFormat: 'd M Y' } };
    },

    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearVehicle()       { this.form.vehicle_ref = '';       this.form.vehicle_plate = ''; },
    clearDocumentType()  { this.form.document_type_ref = ''; this.form.document_type_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/operations/fleet_maintenance/vehicle_documents/vehicle_documents_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        vehicle_plate: String(this.form.vehicle_plate ?? ''),
        document_type_name: String(this.form.document_type_name ?? ''),
        document_number: String(this.form.document_number ?? ''),
        issue_date: String(this.form.issue_date ?? ''),
        expiry_date: String(this.form.expiry_date ?? ''),
        issued_by: String(this.form.issued_by ?? ''),
        attachment: String(this.form.attachment ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/operations/fleet_maintenance/vehicle_documents/vehicle_documents_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.vehicle_ref = '';
      this.form.vehicle_plate = '';
      this.form.document_type_ref = '';
      this.form.document_type_name = '';
      this.form.document_number = '';
      this.form.issue_date = '';
      this.form.expiry_date = '';
      this.form.issued_by = '';
      this.form.attachment = '';
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/operations/fleet_maintenance/vehicle_documents/vehicle_documents_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/operations/fleet_maintenance/vehicle_documents/vehicle_documents_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.vehicle_ref = data.vehicle_ref ?? '';
      this.form.vehicle_plate = data.m_vehicles?.plate_number ?? '';
      this.form.document_type_ref = data.document_type_ref ?? '';
      this.form.document_type_name = data.m_vehicle_document_types?.name ?? '';
      this.form.document_number = data.document_number;
      this.form.issue_date = data.issue_date;
      this.form.expiry_date = data.expiry_date;
      this.form.issued_by = data.issued_by;
      this.form.attachment = data.attachment;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).directive('flatpickr', window.FlatpickrDirective).mount('#vehicle-documents-app');
