<?php /* modules/operations/fleet_maintenance/vehicle_documents/vehicle_documents.php — generated by Generate Module */ ?>

<div id="vehicle-documents-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#vehicleDocumentsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="vehicle-documents-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="vehicle-documents-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Vehicle</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-documents-vehicle-ref" v-model="form.vehicle_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.vehicle_plate" placeholder="Plate number…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vdcVehiclePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearVehicle" v-if="form.vehicle_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Document Type</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-documents-document-type-ref" v-model="form.document_type_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.document_type_name" placeholder="Document type…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vdcDocumentTypePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearDocumentType" v-if="form.document_type_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-documents-document-number" class="col-sm-4 col-form-label">Document Number</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-documents-document-number" v-model="form.document_number" />
      </div>
    </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label for="vehicle-documents-issue-date" class="col-sm-4 col-form-label">Issue Date</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-documents-issue-date" v-flatpickr="datePicker(form.issue_date, (v) => form.issue_date = v)" placeholder="Pick a date…" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-documents-expiry-date" class="col-sm-4 col-form-label">Expiry Date</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-documents-expiry-date" v-flatpickr="datePicker(form.expiry_date, (v) => form.expiry_date = v)" placeholder="Pick a date…" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-documents-issued-by" class="col-sm-4 col-form-label">Issued By</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-documents-issued-by" v-model="form.issued_by" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-documents-attachment" class="col-sm-4 col-form-label">Attachment</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-documents-attachment" v-model="form.attachment" placeholder="File name / URL…" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-documents-remarks" class="col-sm-4 col-form-label">Remarks</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="vehicle-documents-remarks" v-model="form.remarks"></textarea>
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Vehicle Documents saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/vehicle_documents_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/operations/fleet_maintenance/vehicle_documents/vehicle_documents.js"></script>