<?php
// venue_category_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveVenueCategory(array $data): array {
    $ref = consumeNextReference('venue_category');

    $record = supabase_post(SB_API . 'm_venue_categories', [
        'ref' => $ref,
        'venue_category_name' => $data['venue_category_name'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateVenueCategory(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_venue_categories', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_venue_categories?ref=eq.' . urlencode($ref), [
        'venue_category_name' => $data['venue_category_name'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listVenueCategory(): array {
    return supabase_get(SB_API . 'm_venue_categories?select=id,ref,venue_category_name&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listVenueCategory());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveVenueCategory($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateVenueCategory($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_venue_categories', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}