<?php
// vehicle_brand_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveVehicleBrand(array $data): array {
    $ref = consumeNextReference('vehicle_brand');

    return supabase_post(SB_API . 'm_vehicle_brands', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'country' => $data['country'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateVehicleBrand(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_vehicle_brands', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_vehicle_brands?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'country' => $data['country'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listVehicleBrand(): array {
    return supabase_get(SB_API . 'm_vehicle_brands?select=id,ref,code,name,country&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listVehicleBrand());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveVehicleBrand($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateVehicleBrand($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_vehicle_brands', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}