<?php /* modules/human_resources_payroll/salary_setup/payroll_profiles/payroll_profiles.php — generated by Generate Module */ ?>

<div id="payroll-profiles-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#payrollProfilesSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="payroll-profiles-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="payroll-profiles-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label for="payroll-profiles-code" class="col-sm-4 col-form-label">Code</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="payroll-profiles-code" v-model="form.code" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-profiles-name" class="col-sm-4 col-form-label">Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="payroll-profiles-name" v-model="form.name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Currency</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="payroll-profiles-currency-ref" v-model="form.currency_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.currency_name" placeholder="Currency…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#ppCurrencyPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearCurrency" v-if="form.currency_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-profiles-pay-frequency" class="col-sm-4 col-form-label">Pay Frequency</label>
      <div class="col-sm-8">
        <select class="form-select" id="payroll-profiles-pay-frequency" v-model="form.pay_frequency" required>
                  <option value="" disabled>Select…</option>
                  <option value="Weekly">Weekly</option>
                  <option value="Bi-Weekly">Bi-Weekly</option>
                  <option value="Semi-Monthly">Semi-Monthly</option>
                  <option value="Monthly">Monthly</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-profiles-pay-day" class="col-sm-4 col-form-label">Pay Day</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="payroll-profiles-pay-day" v-model.number="form.pay_day" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-profiles-proration-method" class="col-sm-4 col-form-label">Proration Method</label>
      <div class="col-sm-8">
        <select class="form-select" id="payroll-profiles-proration-method" v-model="form.proration_method">
                  <option value="" disabled>Select…</option>
                  <option value="Calendar Days">Calendar Days</option>
                  <option value="Working Days">Working Days</option>
                  <option value="Fixed Divisor">Fixed Divisor</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-profiles-fixed-divisor" class="col-sm-4 col-form-label">Fixed Divisor</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-profiles-fixed-divisor" v-model.number="form.fixed_divisor" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-profiles-remarks" class="col-sm-4 col-form-label">Remarks</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="payroll-profiles-remarks" v-model="form.remarks"></textarea>
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Payroll Profiles saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/payroll_profiles_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/human_resources_payroll/salary_setup/payroll_profiles/payroll_profiles.js"></script>