// payroll_profiles_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Currency picker ──────────────────────────────────────────────────────
  const currencyPicker = $('#ppCurrencyPickerTable').DataTable({
    ajax: { url: '/modules/finance/assets_budgeting/multi_currency/multi_currency_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'currency_code' },
      { data: 'currency_name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#ppCurrencyPickerTable tbody').on('click', 'tr', function () {
    const data = currencyPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('ppCurrencyPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('pp-currency-selected', { detail: data }));
  });

  $('#ppCurrencyPickerModal').on('shown.bs.modal', function () {
    currencyPicker.ajax.reload(null, false);
    currencyPicker.columns.adjust();
  });

  const table = $('#payrollProfilesSearchTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/salary_setup/payroll_profiles/payroll_profiles_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
      { data: 'm_currencies.currency_code', defaultContent: '' },
      { data: 'pay_frequency' },
      { data: 'pay_day' },
      { data: 'proration_method' },
      { data: 'fixed_divisor' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Payroll Profiles records',
    },
  });

  $('#payrollProfilesSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('payrollProfilesSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('payroll_profiles-selected', { detail: data }));
  });

  $('#payrollProfilesSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});