<?php
// customer_types_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveCustomerTypes(array $data): array {
    $ref = consumeNextReference('customer_types');

    return supabase_post(SB_API . 'm_customer_types', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateCustomerTypes(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_customer_types', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_customer_types?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listCustomerTypes(): array {
    return supabase_get(SB_API . 'm_customer_types?select=id,ref,code,name,description&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listCustomerTypes());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveCustomerTypes($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateCustomerTypes($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_customer_types', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}