<?php
// quotation_resources_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveQuotationResources(array $data): array {
    $ref = consumeNextReference('quotation_resources');

    return supabase_post(SB_API . 't_quotation_resources', [
        'ref' => $ref,
        'quotation_ref' => !empty($data['quotation_ref']) ? $data['quotation_ref'] : null,
        'vehicle_type_ref' => !empty($data['vehicle_type_ref']) ? $data['vehicle_type_ref'] : null,
        'quantity' => $data['quantity'] ?? 0,
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateQuotationResources(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('t_quotation_resources', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 't_quotation_resources?ref=eq.' . urlencode($ref), [
        'quotation_ref' => !empty($data['quotation_ref']) ? $data['quotation_ref'] : null,
        'vehicle_type_ref' => !empty($data['vehicle_type_ref']) ? $data['vehicle_type_ref'] : null,
        'quantity' => $data['quantity'] ?? 0,
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listQuotationResources(): array {
    return supabase_get(SB_API . 't_quotation_resources?select=id,ref,quotation_ref,vehicle_type_ref,quantity,remarks,m_quotations(ref),m_vehicle_types(ref,name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listQuotationResources());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveQuotationResources($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateQuotationResources($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('t_quotation_resources', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}
