<?php /* modules/master_files/references/customer_advance/customer_advance.php — generated by Generate Module */ ?>

<div id="customer-advance-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#customerAdvanceSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="customer-advance-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="customer-advance-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <form ref="form">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Customer</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="customer-advance-customer-ref" v-model="form.customer_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.customer_name" placeholder="Customer…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#caCustomerPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearCustomer" v-if="form.customer_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="customer-advance-booking-reference" class="col-sm-4 col-form-label">Booking Reference</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="customer-advance-booking-reference" v-model="form.booking_reference" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="customer-advance-advance-amount" class="col-sm-4 col-form-label">Advance Amount</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="customer-advance-advance-amount" v-model.number="form.advance_amount" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="customer-advance-advance-date" class="col-sm-4 col-form-label">Advance Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="customer-advance-advance-date" v-model="form.advance_date" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="customer-advance-payment-method" class="col-sm-4 col-form-label">Payment Method</label>
      <div class="col-sm-8">
        <select class="form-select" id="customer-advance-payment-method" v-model="form.payment_method">
                  <option value="" disabled>Select…</option>
                  <option value="Cash">Cash</option>
                  <option value="Bank Transfer">Bank Transfer</option>
                  <option value="Cheque">Cheque</option>
                  <option value="Card">Card</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="customer-advance-notes" class="col-sm-4 col-form-label">Notes</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="customer-advance-notes" v-model="form.notes"></textarea>
      </div>
    </div>
    </form>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Customer Advance saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/customer_advance_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/references/customer_advance/customer_advance.js"></script>