// customer_advance.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      customer_ref: '',
      customer_name: '',
      booking_reference: '',
      advance_amount: 0,
      advance_date: '',
      payment_method: '',
      notes: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.customer_ref !== '' ||
        this.form.booking_reference !== '' ||
        this.form.advance_amount !== 0 ||
        this.form.advance_date !== '' ||
        this.form.payment_method !== '' ||
        this.form.notes !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('customer_advance-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('ca-customer-selected', (e) => {
      this.form.customer_ref  = e.detail.ref;
      this.form.customer_name = e.detail.customer_name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearCustomer() { this.form.customer_ref = ''; this.form.customer_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/references/customer_advance/customer_advance_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        customer_ref: String(this.form.customer_ref ?? ''),
        customer_name: String(this.form.customer_name ?? ''),
        booking_reference: String(this.form.booking_reference ?? ''),
        advance_amount: String(this.form.advance_amount ?? ''),
        advance_date: String(this.form.advance_date ?? ''),
        payment_method: String(this.form.payment_method ?? ''),
        notes: String(this.form.notes ?? ''),
          });
          window.open('/modules/master_files/references/customer_advance/customer_advance_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.customer_ref = '';
      this.form.customer_name = '';
      this.form.booking_reference = '';
      this.form.advance_amount = 0;
      this.form.advance_date = '';
      this.form.payment_method = '';
      this.form.notes = '';
    },

    onSave() {
      if (!this.isDirty) return;
      if (this.$refs.form && !this.$refs.form.reportValidity()) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/references/customer_advance/customer_advance_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = err.response?.data?.error || 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/references/customer_advance/customer_advance_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.customer_ref = data.customer_ref ?? '';
      this.form.customer_name = data.m_customers?.customer_name ?? '';
      this.form.booking_reference = data.booking_reference;
      this.form.advance_amount = data.advance_amount;
      this.form.advance_date = data.advance_date;
      this.form.payment_method = data.payment_method;
      this.form.notes = data.notes;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#customer-advance-app');