// customer_advance_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Customer picker ──────────────────────────────────────────────────────
  const customerPicker = $('#caCustomerPickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/customer_master_file/customer_master_file_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'customer_name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#caCustomerPickerTable tbody').on('click', 'tr', function () {
    const data = customerPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('caCustomerPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ca-customer-selected', { detail: data }));
  });

  $('#caCustomerPickerModal').on('shown.bs.modal', function () {
    customerPicker.ajax.reload(null, false);
    customerPicker.columns.adjust();
  });

  const table = $('#customerAdvanceSearchTable').DataTable({
    ajax: { url: '/modules/master_files/references/customer_advance/customer_advance_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_customers.customer_name', defaultContent: '—' },
      { data: 'booking_reference' },
      { data: 'advance_amount' },
      { data: 'advance_date' },
      { data: 'payment_method' },
      { data: 'notes' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Customer Advance records',
    },
  });

  $('#customerAdvanceSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('customerAdvanceSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('customer_advance-selected', { detail: data }));
  });
  $('#customerAdvanceSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});