<?php /* modules/human_resources_payroll/payroll_processing/payroll_runs/payroll_runs.php — generated by Generate Module */ ?>

<div id="payroll-runs-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#payrollRunsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel" :disabled="cancelling">
              <span v-if="cancelling" class="spinner-border spinner-border-sm me-2" role="status"></span>Cancel
            </button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="payroll-runs-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="payroll-runs-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Payroll Period</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="payroll-runs-payroll-period-ref" v-model="form.payroll_period_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.payroll_period_name" placeholder="Payroll period…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#prPayrollPeriodPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearPayrollPeriod" v-if="form.payroll_period_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-run-date" class="col-sm-4 col-form-label">Run Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="payroll-runs-run-date" v-model="form.run_date" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-description" class="col-sm-4 col-form-label">Description</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="payroll-runs-description" v-model="form.description"></textarea>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-payroll-status" class="col-sm-4 col-form-label">Payroll Status</label>
      <div class="col-sm-8">
        <select class="form-select" id="payroll-runs-payroll-status" v-model="form.payroll_status" required>
                  <option value="" disabled>Select…</option>
                  <option value="Draft">Draft</option>
                  <option value="Processing">Processing</option>
                  <option value="Completed">Completed</option>
                  <option value="Paid">Paid</option>
                  <option value="Cancelled" disabled>Cancelled</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-total-gross-amount" class="col-sm-4 col-form-label">Total Gross Amount</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-runs-total-gross-amount" v-model.number="form.total_gross_amount" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-total-deduction-amount" class="col-sm-4 col-form-label">Total Deduction Amount</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-runs-total-deduction-amount" v-model.number="form.total_deduction_amount" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-total-net-amount" class="col-sm-4 col-form-label">Total Net Amount</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-runs-total-net-amount" v-model.number="form.total_net_amount" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-runs-remarks" class="col-sm-4 col-form-label">Remarks</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="payroll-runs-remarks" v-model="form.remarks"></textarea>
      </div>
    </div>
          </div>
        </div>

        <!-- Employee payrolls — auto-generated from the Payroll Period; each employee row has its own nested salary-component lines -->
        <hr class="my-4" />
        <div class="d-flex justify-content-between align-items-center flex-wrap gap-2 mb-3">
          <h6 class="mb-0">Employee Payrolls</h6>
          <div class="d-flex align-items-center gap-2">
            <span class="text-muted small" v-if="!form.payroll_period_ref">Select a Payroll Period to enable payroll calculation.</span>
            <button type="button" class="btn btn-primary" @click="onGeneratePayroll" :disabled="!form.payroll_period_ref || generating">
              <span v-if="generating" class="spinner-border spinner-border-sm me-2" role="status"></span>
              <i v-else class="bi bi-gear-fill me-2"></i>Generate Payroll
            </button>
          </div>
        </div>

        <div class="alert alert-warning py-2 px-3 small" v-if="skipped.length">
          <div class="fw-semibold mb-1"><i class="bi bi-exclamation-triangle me-1"></i>{{ skipped.length }} employment record(s) skipped:</div>
          <ul class="mb-0 ps-3">
            <li v-for="(s, si) in skipped" :key="si">{{ s.employment_record_name }} ({{ s.employment_record_ref }}) — {{ s.reason }}</li>
          </ul>
        </div>

        <p class="text-muted small" v-if="!form.employees.length">No employee payrolls yet — select a Payroll Period and click Generate Payroll.</p>

        <div class="mb-3" style="overflow:visible" v-if="form.employees.length">
          <div v-for="(emp, ei) in form.employees" :key="ei" class="border rounded-3 p-3 mb-3 position-relative bg-body-tertiary">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <span class="fw-semibold small text-muted">Employee {{ ei + 1 }}</span>
              <button type="button" class="btn btn-sm btn-outline-danger" @click="removeEmployee(ei)" title="Remove employee">
                <i class="bi bi-trash"></i>
              </button>
            </div>

            <div class="row g-2 mb-2">
              <div class="col-md-4">
                <picker-field label="Employment Record" placeholder="Employment record…" :ref-value="emp.employment_record_ref" :name-value="emp.employment_record_name" @open="openEmploymentRecordPicker(ei)" @clear="clearEmploymentRecordField(ei)"></picker-field>
              </div>
              <div class="col-md-2">
                <label class="form-label small text-muted mb-1">Basic Salary</label>
                <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="emp.basic_salary" readonly />
              </div>
              <div class="col-md-2">
                <label class="form-label small text-muted mb-1">Gross Earnings</label>
                <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="emp.gross_earnings" readonly />
              </div>
              <div class="col-md-2">
                <label class="form-label small text-muted mb-1">Total Deductions</label>
                <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="emp.total_deductions" readonly />
              </div>
              <div class="col-md-2">
                <label class="form-label small text-muted mb-1">Net Salary</label>
                <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="emp.net_salary" readonly />
              </div>
            </div>

            <div class="row g-2 mb-3">
              <div class="col-md-3">
                <label class="form-label small text-muted mb-1">Payment Status</label>
                <select class="form-select form-select-sm" v-model="emp.payment_status">
                  <option value="" disabled>Select…</option>
                  <option value="Pending">Pending</option>
                  <option value="Paid">Paid</option>
                </select>
              </div>
              <div class="col-md-3">
                <label class="form-label small text-muted mb-1">Paid Date</label>
                <input type="date" class="form-control form-control-sm" v-model="emp.paid_date" />
              </div>
              <div class="col-md-6">
                <label class="form-label small text-muted mb-1">Remarks</label>
                <input type="text" class="form-control form-control-sm" v-model="emp.remarks" placeholder="Remarks…" />
              </div>
            </div>

            <div class="ps-3 border-start">
              <div class="small fw-semibold text-muted mb-2">Salary Component Lines</div>
              <div v-for="(line, li) in emp.lines" :key="li" class="row g-2 mb-2 align-items-end">
                <div class="col-md-4">
                  <picker-field label="Salary Component" placeholder="Component…" :ref-value="line.salary_component_ref" :name-value="line.salary_component_name" @open="openSalaryComponentPicker(ei, li)" @clear="clearLineField(ei, li)"></picker-field>
                </div>
                <div class="col-md-2">
                  <label class="form-label small text-muted mb-1">Quantity</label>
                  <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="line.quantity" readonly />
                </div>
                <div class="col-md-2">
                  <label class="form-label small text-muted mb-1">Rate</label>
                  <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="line.rate" readonly />
                </div>
                <div class="col-md-3">
                  <label class="form-label small text-muted mb-1">Amount</label>
                  <input type="number" step="0.01" class="form-control form-control-sm" v-model.number="line.amount" readonly />
                </div>
                <div class="col-md-1">
                  <button type="button" class="btn btn-sm btn-outline-danger" @click="removeLine(ei, li)" title="Remove line">
                    <i class="bi bi-trash"></i>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Payroll Runs saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/payroll_runs_search.php'; ?>
<?php include __DIR__ . '/payroll_runs_line_pickers.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/human_resources_payroll/payroll_processing/payroll_runs/payroll_runs.js"></script>