// payroll_runs_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Payroll Period picker (header) ───────────────────────────────────────
  const payrollPeriodPicker = $('#prPayrollPeriodPickerTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#prPayrollPeriodPickerTable tbody').on('click', 'tr', function () {
    const data = payrollPeriodPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('prPayrollPeriodPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('pr-payroll-period-selected', { detail: data }));
  });

  $('#prPayrollPeriodPickerModal').on('shown.bs.modal', function () {
    payrollPeriodPicker.ajax.reload(null, false);
    payrollPeriodPicker.columns.adjust();
  });

  const table = $('#payrollRunsSearchTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/payroll_processing/payroll_runs/payroll_runs_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_payroll_periods.name', defaultContent: '' },
      { data: 'run_date' },
      { data: 'description' },
      { data: 'payroll_status' },
      { data: 'total_gross_amount' },
      { data: 'total_deduction_amount' },
      { data: 'total_net_amount' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Payroll Runs records',
    },
  });

  $('#payrollRunsSearchTable tbody').on('click', 'tr', function () {
    const row = table.row(this).data();
    if (!row) return;
    axios.get('/modules/human_resources_payroll/payroll_processing/payroll_runs/payroll_runs_data.php?action=get&ref=' + encodeURIComponent(row.ref))
      .then(res => {
        bootstrap.Modal.getInstance(document.getElementById('payrollRunsSearchModal')).hide();
        document.dispatchEvent(new CustomEvent('payroll_runs-selected', { detail: res.data }));
      });
  });

  $('#payrollRunsSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});