// employee_salary_structure_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Employee picker ──────────────────────────────────────────────────────
  const employeePicker = $('#essEmployeePickerTable').DataTable({
    ajax: { url: '/modules/master_files/people/employee_master/employee_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'full_name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#essEmployeePickerTable tbody').on('click', 'tr', function () {
    const data = employeePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('essEmployeePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ess-employee-selected', { detail: data }));
  });

  $('#essEmployeePickerModal').on('shown.bs.modal', function () {
    employeePicker.ajax.reload(null, false);
    employeePicker.columns.adjust();
  });

  // ── Salary Component picker ──────────────────────────────────────────────
  const salaryComponentPicker = $('#essSalaryComponentPickerTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/salary_setup/salary_components/salary_components_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#essSalaryComponentPickerTable tbody').on('click', 'tr', function () {
    const data = salaryComponentPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('essSalaryComponentPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('ess-salary-component-selected', { detail: data }));
  });

  $('#essSalaryComponentPickerModal').on('shown.bs.modal', function () {
    salaryComponentPicker.ajax.reload(null, false);
    salaryComponentPicker.columns.adjust();
  });

  const table = $('#employeeSalaryStructureSearchTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/salary_setup/employee_salary_structure/employee_salary_structure_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_employees.full_name', defaultContent: '' },
      { data: 'm_salary_components.name', defaultContent: '' },
      { data: 'amount' },
      { data: 'effective_from' },
      { data: 'effective_to' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Employee Salary Structure records',
    },
  });

  $('#employeeSalaryStructureSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('employeeSalaryStructureSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('employee_salary_structure-selected', { detail: data }));
  });

  $('#employeeSalaryStructureSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});