// employee_salary_structure.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      employee_ref: '',
      employee_name: '',
      salary_component_ref: '',
      salary_component_name: '',
      amount: 0,
      effective_from: '',
      effective_to: '',
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.employee_ref !== '' ||
        this.form.salary_component_ref !== '' ||
        this.form.amount !== 0 ||
        this.form.effective_from !== '' ||
        this.form.effective_to !== '' ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('employee_salary_structure-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('ess-employee-selected', (e) => {
      this.form.employee_ref  = e.detail.ref;
      this.form.employee_name = e.detail.full_name;
    });
    document.addEventListener('ess-salary-component-selected', (e) => {
      this.form.salary_component_ref  = e.detail.ref;
      this.form.salary_component_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearEmployee()        { this.form.employee_ref = '';        this.form.employee_name = ''; },
    clearSalaryComponent() { this.form.salary_component_ref = ''; this.form.salary_component_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/human_resources_payroll/salary_setup/employee_salary_structure/employee_salary_structure_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        employee_name: String(this.form.employee_name ?? ''),
        salary_component_name: String(this.form.salary_component_name ?? ''),
        amount: String(this.form.amount ?? ''),
        effective_from: String(this.form.effective_from ?? ''),
        effective_to: String(this.form.effective_to ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/human_resources_payroll/salary_setup/employee_salary_structure/employee_salary_structure_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.employee_ref = '';
      this.form.employee_name = '';
      this.form.salary_component_ref = '';
      this.form.salary_component_name = '';
      this.form.amount = 0;
      this.form.effective_from = '';
      this.form.effective_to = '';
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/human_resources_payroll/salary_setup/employee_salary_structure/employee_salary_structure_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/human_resources_payroll/salary_setup/employee_salary_structure/employee_salary_structure_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.employee_ref = data.employee_ref ?? '';
      this.form.employee_name = data.m_employees?.full_name ?? '';
      this.form.salary_component_ref = data.salary_component_ref ?? '';
      this.form.salary_component_name = data.m_salary_components?.name ?? '';
      this.form.amount = data.amount;
      this.form.effective_from = data.effective_from;
      this.form.effective_to = data.effective_to;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#employee-salary-structure-app');