<?php
// employee_salary_structure_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveEmployeeSalaryStructure(array $data): array {
    $ref = consumeNextReference('employee_salary_structure');

    return supabase_post(SB_API . 'm_employee_salary_structures', [
        'ref' => $ref,
        'employee_ref' => !empty($data['employee_ref']) ? $data['employee_ref'] : null,
        'salary_component_ref' => !empty($data['salary_component_ref']) ? $data['salary_component_ref'] : null,
        'amount' => $data['amount'] ?? 0,
        'effective_from' => !empty($data['effective_from']) ? $data['effective_from'] : null,
        'effective_to' => !empty($data['effective_to']) ? $data['effective_to'] : null,
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateEmployeeSalaryStructure(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_employee_salary_structures', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_employee_salary_structures?ref=eq.' . urlencode($ref), [
        'employee_ref' => !empty($data['employee_ref']) ? $data['employee_ref'] : null,
        'salary_component_ref' => !empty($data['salary_component_ref']) ? $data['salary_component_ref'] : null,
        'amount' => $data['amount'] ?? 0,
        'effective_from' => !empty($data['effective_from']) ? $data['effective_from'] : null,
        'effective_to' => !empty($data['effective_to']) ? $data['effective_to'] : null,
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listEmployeeSalaryStructure(): array {
    return supabase_get(SB_API . 'm_employee_salary_structures?select=id,ref,employee_ref,salary_component_ref,amount,effective_from,effective_to,remarks,m_employees(full_name),m_salary_components(name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listEmployeeSalaryStructure());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveEmployeeSalaryStructure($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateEmployeeSalaryStructure($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_employee_salary_structures', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}