<?php
// site_visit_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveSiteVisit(array $data): array {
    $ref = consumeNextReference('site_visit');

    $record = supabase_post(SB_API . 'm_site_visits', [
        'ref' => $ref,
        'venue_ref' => !empty($data['venue_ref']) ? $data['venue_ref'] : null,
        'visit_date' => !empty($data['visit_date']) ? $data['visit_date'] : null,
        'visit_time' => $data['visit_time'] ?? '',
        'visit_status' => $data['visit_status'] ?? '',
        'notes' => $data['notes'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateSiteVisit(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_site_visits', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_site_visits?ref=eq.' . urlencode($ref), [
        'venue_ref' => !empty($data['venue_ref']) ? $data['venue_ref'] : null,
        'visit_date' => !empty($data['visit_date']) ? $data['visit_date'] : null,
        'visit_time' => $data['visit_time'] ?? '',
        'visit_status' => $data['visit_status'] ?? '',
        'notes' => $data['notes'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listSiteVisit(): array {
    return supabase_get(SB_API . 'm_site_visits?select=id,ref,venue_ref,visit_date,visit_time,visit_status,notes,m_venues(venue_name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listSiteVisit());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveSiteVisit($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateSiteVisit($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_site_visits', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}