// site_visit_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Venue picker ──────────────────────────────────────────────────────────
  const venuePicker = $('#svVenuePickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/venue_master/venue_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'venue_name' },
      { data: 'address' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#svVenuePickerTable tbody').on('click', 'tr', function () {
    const data = venuePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('svVenuePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('sv-venue-selected', { detail: data }));
  });

  $('#svVenuePickerModal').on('shown.bs.modal', function () {
    venuePicker.ajax.reload(null, false);
    venuePicker.columns.adjust();
  });

  const table = $('#siteVisitSearchTable').DataTable({
    ajax: { url: '/modules/operations/event_planning/site_visit/site_visit_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_venues.venue_name', defaultContent: '' },
      { data: 'visit_date' },
      { data: 'visit_time' },
      { data: 'visit_status' },
      { data: 'notes' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Site Visit records',
    },
  });

  $('#siteVisitSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('siteVisitSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('site_visit-selected', { detail: data }));
  });
  $('#siteVisitSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});