<?php /* modules/operations/event_planning/site_visit/site_visit.php — generated by Generate Module */ ?>

<div id="site-visit-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#siteVisitSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="site-visit-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="site-visit-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <form ref="form">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Venue</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="site-visit-venue-ref" v-model="form.venue_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.venue_name" placeholder="Venue…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#svVenuePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearVenue" v-if="form.venue_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="site-visit-visit-date" class="col-sm-4 col-form-label">Visit Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="site-visit-visit-date" v-model="form.visit_date" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="site-visit-visit-time" class="col-sm-4 col-form-label">Visit Time</label>
      <div class="col-sm-8">
        <input type="time" class="form-control" id="site-visit-visit-time" v-model="form.visit_time" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="site-visit-visit-status" class="col-sm-4 col-form-label">Status</label>
      <div class="col-sm-8">
        <select class="form-select" id="site-visit-visit-status" v-model="form.visit_status" required>
                  <option value="" disabled>Select…</option>
                  <option value="Scheduled">Scheduled</option>
                  <option value="Completed">Completed</option>
                  <option value="Cancelled">Cancelled</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="site-visit-notes" class="col-sm-4 col-form-label">Notes</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="site-visit-notes" v-model="form.notes"></textarea>
      </div>
    </div>
    </form>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Site Visit saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/site_visit_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/operations/event_planning/site_visit/site_visit.js"></script>