// site_visit.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      venue_ref: '',
      venue_name: '',
      visit_date: '',
      visit_time: '',
      visit_status: '',
      notes: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.venue_ref !== '' ||
        this.form.visit_date !== '' ||
        this.form.visit_time !== '' ||
        this.form.visit_status !== '' ||
        this.form.notes !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('site_visit-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('sv-venue-selected', (e) => {
      this.form.venue_ref  = e.detail.ref;
      this.form.venue_name = e.detail.venue_name;
    });
  },

  methods: {
    clearVenue() { this.form.venue_ref = ''; this.form.venue_name = ''; },

    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/operations/event_planning/site_visit/site_visit_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        venue_name: String(this.form.venue_name ?? ''),
        visit_date: String(this.form.visit_date ?? ''),
        visit_time: String(this.form.visit_time ?? ''),
        visit_status: String(this.form.visit_status ?? ''),
        notes: String(this.form.notes ?? ''),
          });
          window.open('/modules/operations/event_planning/site_visit/site_visit_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.venue_ref = '';
      this.form.venue_name = '';
      this.form.visit_date = '';
      this.form.visit_time = '';
      this.form.visit_status = '';
      this.form.notes = '';
    },

    onSave() {
      if (!this.isDirty) return;
      if (!this.form.venue_ref) { this.error = 'Please select a Venue.'; return; }
      if (this.$refs.form && !this.$refs.form.reportValidity()) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/operations/event_planning/site_visit/site_visit_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = err.response?.data?.error || 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/operations/event_planning/site_visit/site_visit_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.venue_ref = data.venue_ref ?? '';
      this.form.venue_name = data.m_venues?.venue_name ?? data.venue_ref ?? '';
      this.form.visit_date = data.visit_date;
      this.form.visit_time = data.visit_time;
      this.form.visit_status = data.visit_status;
      this.form.notes = data.notes;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#site-visit-app');