<?php
// freelance_crew_payment_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveFreelanceCrewPayment(array $data): array {
    $ref = consumeNextReference('freelance_crew_payment');

    $record = supabase_post(SB_API . 'm_freelance_crew_payments', [
        'ref' => $ref,
        'crew_ref' => !empty($data['crew_ref']) ? $data['crew_ref'] : null,
        'venue_ref' => !empty($data['venue_ref']) ? $data['venue_ref'] : null,
        'work_date' => !empty($data['work_date']) ? $data['work_date'] : null,
        'event_description' => $data['event_description'] ?? '',
        'days_worked' => $data['days_worked'] ?? 0,
        'daily_rate' => $data['daily_rate'] ?? 0,
        'amount' => $data['amount'] ?? 0,
        'payment_status' => $data['payment_status'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateFreelanceCrewPayment(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_freelance_crew_payments', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_freelance_crew_payments?ref=eq.' . urlencode($ref), [
        'crew_ref' => !empty($data['crew_ref']) ? $data['crew_ref'] : null,
        'venue_ref' => !empty($data['venue_ref']) ? $data['venue_ref'] : null,
        'work_date' => !empty($data['work_date']) ? $data['work_date'] : null,
        'event_description' => $data['event_description'] ?? '',
        'days_worked' => $data['days_worked'] ?? 0,
        'daily_rate' => $data['daily_rate'] ?? 0,
        'amount' => $data['amount'] ?? 0,
        'payment_status' => $data['payment_status'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listFreelanceCrewPayment(): array {
    return supabase_get(SB_API . 'm_freelance_crew_payments?select=id,ref,crew_ref,venue_ref,work_date,event_description,days_worked,daily_rate,amount,payment_status,remarks,m_freelance_crew(full_name),m_venues(venue_name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listFreelanceCrewPayment());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveFreelanceCrewPayment($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateFreelanceCrewPayment($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_freelance_crew_payments', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}