// freelance_crew_payment_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Freelance Crew picker ────────────────────────────────────────────────
  const crewPicker = $('#fcpCrewPickerTable').DataTable({
    ajax: { url: '/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'full_name' },
      { data: 'role_type' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#fcpCrewPickerTable tbody').on('click', 'tr', function () {
    const data = crewPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('fcpCrewPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('fcp-crew-selected', { detail: data }));
  });

  $('#fcpCrewPickerModal').on('shown.bs.modal', function () {
    crewPicker.ajax.reload(null, false);
    crewPicker.columns.adjust();
  });

  // ── Venue picker ──────────────────────────────────────────────────────────
  const venuePicker = $('#fcpVenuePickerTable').DataTable({
    ajax: { url: '/modules/master_files/references/venue_master/venue_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'venue_name' },
      { data: 'address' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#fcpVenuePickerTable tbody').on('click', 'tr', function () {
    const data = venuePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('fcpVenuePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('fcp-venue-selected', { detail: data }));
  });

  $('#fcpVenuePickerModal').on('shown.bs.modal', function () {
    venuePicker.ajax.reload(null, false);
    venuePicker.columns.adjust();
  });

  const table = $('#freelanceCrewPaymentSearchTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/hr_operations/freelance_crew_payment/freelance_crew_payment_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_freelance_crew.full_name', defaultContent: '' },
      { data: 'm_venues.venue_name', defaultContent: '' },
      { data: 'work_date' },
      { data: 'event_description' },
      { data: 'days_worked' },
      { data: 'daily_rate' },
      { data: 'amount' },
      { data: 'payment_status' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Freelance Crew Payment records',
    },
  });

  $('#freelanceCrewPaymentSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('freelanceCrewPaymentSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('freelance_crew_payment-selected', { detail: data }));
  });
  $('#freelanceCrewPaymentSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});