<?php
// venue_master_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveVenueMaster(array $data): array {
    $ref = consumeNextReference('venue_master');

    $record = supabase_post(SB_API . 'm_venues', [
        'ref' => $ref,
        'venue_name' => $data['venue_name'] ?? '',
        'address' => $data['address'] ?? '',
        'venue_category_ref' => !empty($data['venue_category_ref']) ? $data['venue_category_ref'] : null,
        'capacity' => $data['capacity'] ?? 0,
        'layout' => $data['layout'] ?? '',
        'contact_name' => $data['contact_name'] ?? '',
        'contact_phone' => $data['contact_phone'] ?? '',
        'contact_email' => $data['contact_email'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateVenueMaster(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_venues', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_venues?ref=eq.' . urlencode($ref), [
        'venue_name' => $data['venue_name'] ?? '',
        'address' => $data['address'] ?? '',
        'venue_category_ref' => !empty($data['venue_category_ref']) ? $data['venue_category_ref'] : null,
        'capacity' => $data['capacity'] ?? 0,
        'layout' => $data['layout'] ?? '',
        'contact_name' => $data['contact_name'] ?? '',
        'contact_phone' => $data['contact_phone'] ?? '',
        'contact_email' => $data['contact_email'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listVenueMaster(): array {
    return supabase_get(SB_API . 'm_venues?select=id,ref,venue_name,address,venue_category_ref,capacity,layout,contact_name,contact_phone,contact_email,m_venue_categories(ref,venue_category_name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listVenueMaster());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveVenueMaster($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateVenueMaster($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_venues', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}