<?php /* modules/master_files/references/venue_master/venue_master.php — generated by Generate Module */ ?>

<div id="venue-master-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#venueMasterSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="venue-master-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="venue-master-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <form ref="form">
    <div class="row mb-3">
      <label for="venue-master-venue-name" class="col-sm-4 col-form-label">Venue Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="venue-master-venue-name" v-model="form.venue_name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="venue-master-address" class="col-sm-4 col-form-label">Address</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="venue-master-address" v-model="form.address"></textarea>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Venue Category</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="venue-master-venue-category-ref" v-model="form.venue_category_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.venue_category_name" placeholder="Venue category…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vnVenueCategoryPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearVenueCategory" v-if="form.venue_category_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="venue-master-capacity" class="col-sm-4 col-form-label">Capacity</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="venue-master-capacity" v-model.number="form.capacity" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="venue-master-layout" class="col-sm-4 col-form-label">Layout</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="venue-master-layout" v-model="form.layout"></textarea>
      </div>
    </div>
    <div class="row mb-3">
      <label for="venue-master-contact-name" class="col-sm-4 col-form-label">Contact Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="venue-master-contact-name" v-model="form.contact_name" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="venue-master-contact-phone" class="col-sm-4 col-form-label">Contact Phone</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="venue-master-contact-phone" v-model="form.contact_phone" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="venue-master-contact-email" class="col-sm-4 col-form-label">Contact Email</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="venue-master-contact-email" v-model="form.contact_email" />
      </div>
    </div>
    </form>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Venue Master saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/venue_master_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/references/venue_master/venue_master.js"></script>