// vehicle_odometer_readings.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      vehicle_ref: '',
      vehicle_plate: '',
      reading_date: '',
      odometer_km: 0,
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.vehicle_ref !== '' ||
        this.form.reading_date !== '' ||
        this.form.odometer_km !== 0 ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('vehicle_odometer_readings-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('vod-vehicle-selected', (e) => {
      this.form.vehicle_ref   = e.detail.ref;
      this.form.vehicle_plate = e.detail.plate_number;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearVehicle() { this.form.vehicle_ref = ''; this.form.vehicle_plate = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/operations/fleet_maintenance/vehicle_odometer_readings/vehicle_odometer_readings_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        vehicle_plate: String(this.form.vehicle_plate ?? ''),
        reading_date: String(this.form.reading_date ?? ''),
        odometer_km: String(this.form.odometer_km ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/operations/fleet_maintenance/vehicle_odometer_readings/vehicle_odometer_readings_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.vehicle_ref = '';
      this.form.vehicle_plate = '';
      this.form.reading_date = '';
      this.form.odometer_km = 0;
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/operations/fleet_maintenance/vehicle_odometer_readings/vehicle_odometer_readings_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/operations/fleet_maintenance/vehicle_odometer_readings/vehicle_odometer_readings_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.vehicle_ref = data.vehicle_ref ?? '';
      this.form.vehicle_plate = data.m_vehicles?.plate_number ?? '';
      this.form.reading_date = data.reading_date;
      this.form.odometer_km = data.odometer_km;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#vehicle-odometer-readings-app');
