<?php
// vehicle_odometer_readings_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveVehicleOdometerReadings(array $data): array {
    $ref = consumeNextReference('vehicle_odometer_readings');

    return supabase_post(SB_API . 't_vehicle_odometer', [
        'ref' => $ref,
        'vehicle_ref' => !empty($data['vehicle_ref']) ? $data['vehicle_ref'] : null,
        'reading_date' => !empty($data['reading_date']) ? $data['reading_date'] : null,
        'odometer_km' => $data['odometer_km'] ?? 0,
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateVehicleOdometerReadings(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('t_vehicle_odometer', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 't_vehicle_odometer?ref=eq.' . urlencode($ref), [
        'vehicle_ref' => !empty($data['vehicle_ref']) ? $data['vehicle_ref'] : null,
        'reading_date' => !empty($data['reading_date']) ? $data['reading_date'] : null,
        'odometer_km' => $data['odometer_km'] ?? 0,
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listVehicleOdometerReadings(): array {
    return supabase_get(SB_API . 't_vehicle_odometer?select=id,ref,vehicle_ref,reading_date,odometer_km,remarks,m_vehicles(ref,plate_number)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listVehicleOdometerReadings());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveVehicleOdometerReadings($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateVehicleOdometerReadings($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('t_vehicle_odometer', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}
