<?php
// salary_assignments_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveSalaryAssignments(array $data): array {
    $ref = consumeNextReference('salary_assignments');
    $actorRef = current_user()['ref'] ?? null;

    $header = supabase_post(SB_API . 'm_salary_assignments', [
        'ref' => $ref,
        'employment_record_ref' => !empty($data['employment_record_ref']) ? $data['employment_record_ref'] : null,
        'currency_ref' => !empty($data['currency_ref']) ? $data['currency_ref'] : null,
        'effective_from' => !empty($data['effective_from']) ? $data['effective_from'] : null,
        'effective_to' => !empty($data['effective_to']) ? $data['effective_to'] : null,
        'remarks' => $data['remarks'] ?? '',
        'created_by' => $actorRef,
        'updated_by' => $actorRef,
    ]);

    if (empty($header)) {
        return $header;
    }

    $details = [];
    foreach ($data['details'] ?? [] as $i => $line) {
        if (empty($line['salary_component_ref'])) continue;
        $details[] = supabase_post(SB_API . 'm_salary_assignment_details', [
            'salary_assignment_ref' => $ref,
            'line_no' => $i + 1,
            'salary_component_ref' => $line['salary_component_ref'],
            'value' => $line['value'] ?? 0,
            'created_by' => $actorRef,
            'updated_by' => $actorRef,
        ]);
    }

    $header['details'] = $details;
    return $header;
}

function updateSalaryAssignments(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '') {
        http_response_code(422);
        return ['error' => 'Salary assignment ref is required.'];
    }
    $actorRef = current_user()['ref'] ?? null;

    $header = supabase_patch(SB_API . 'm_salary_assignments?ref=eq.' . urlencode($ref), [
        'employment_record_ref' => !empty($data['employment_record_ref']) ? $data['employment_record_ref'] : null,
        'currency_ref' => !empty($data['currency_ref']) ? $data['currency_ref'] : null,
        'effective_from' => !empty($data['effective_from']) ? $data['effective_from'] : null,
        'effective_to' => !empty($data['effective_to']) ? $data['effective_to'] : null,
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => $actorRef,
    ]);

    if (empty($header)) {
        return $header;
    }

    supabase_delete(SB_API . 'm_salary_assignment_details?salary_assignment_ref=eq.' . urlencode($ref));

    $details = [];
    foreach ($data['details'] ?? [] as $i => $line) {
        if (empty($line['salary_component_ref'])) continue;
        $details[] = supabase_post(SB_API . 'm_salary_assignment_details', [
            'salary_assignment_ref' => $ref,
            'line_no' => $i + 1,
            'salary_component_ref' => $line['salary_component_ref'],
            'value' => $line['value'] ?? 0,
            'created_by' => $actorRef,
            'updated_by' => $actorRef,
        ]);
    }

    $header['details'] = $details;
    return $header;
}

function listSalaryAssignments(): array {
    return supabase_get(SB_API . 'm_salary_assignments?select=id,ref,employment_record_ref,currency_ref,effective_from,effective_to,remarks,m_employment_records(ref,m_employees(full_name)),m_currencies(currency_code,currency_name),m_salary_assignment_details(salary_component_ref,value,line_no,m_salary_components(name))&m_salary_assignment_details.order=line_no.asc&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listSalaryAssignments());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveSalaryAssignments($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateSalaryAssignments($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_salary_assignments', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}