<?php /* modules/human_resources_payroll/salary_setup/salary_assignments/salary_assignments.php — generated by Generate Module */ ?>

<div id="salary-assignments-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#salaryAssignmentsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="salary-assignments-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="salary-assignments-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Employment Record</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="salary-assignments-employment-record-ref" v-model="form.employment_record_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.employment_record_name" placeholder="Employment record…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#saEmploymentRecordPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearEmploymentRecord" v-if="form.employment_record_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Currency</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="salary-assignments-currency-ref" v-model="form.currency_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.currency_name" placeholder="Currency…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#saCurrencyPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearCurrency" v-if="form.currency_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-assignments-effective-from" class="col-sm-4 col-form-label">Effective From</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="salary-assignments-effective-from" v-model="form.effective_from" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-assignments-effective-to" class="col-sm-4 col-form-label">Effective To</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="salary-assignments-effective-to" v-model="form.effective_to" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="salary-assignments-remarks" class="col-sm-4 col-form-label">Remarks</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="salary-assignments-remarks" v-model="form.remarks"></textarea>
      </div>
    </div>
          </div>
        </div>

        <h6 class="mt-2 mb-3">Salary Assignment Details</h6>
        <div class="table-responsive mb-2" style="overflow:visible">
          <table class="table table-bordered table-sm align-middle">
            <thead class="table-light">
              <tr>
                <th style="width:4%">#</th>
                <th>Salary Component</th>
                <th style="width:20%">Value</th>
                <th style="width:6%"></th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="(line, i) in form.details" :key="i">
                <td class="text-center text-muted small">{{ i + 1 }}</td>
                <td>
                  <div class="input-group input-group-sm">
                    <input type="text" class="form-control font-monospace" v-model="line.salary_component_ref" placeholder="Ref…" readonly style="max-width:120px" />
                    <input type="text" class="form-control" v-model="line.salary_component_name" placeholder="Salary component…" readonly />
                    <button class="btn btn-outline-primary" type="button" @click="openComponentPicker(i)" data-bs-toggle="modal" data-bs-target="#saSalaryComponentPickerModal">
                      <i class="bi bi-search"></i>
                    </button>
                  </div>
                </td>
                <td><input type="number" class="form-control form-control-sm text-end" step="0.01" v-model.number="line.value" /></td>
                <td class="text-center">
                  <button type="button" class="btn btn-sm btn-outline-danger" @click="removeDetailLine(i)" :disabled="form.details.length <= 1">
                    <i class="bi bi-trash"></i>
                  </button>
                </td>
              </tr>
              <tr @click="addDetailLine" style="cursor:pointer">
                <td colspan="4" class="text-center py-2 text-secondary" style="border-top:2px dashed #dee2e6;background:#f8f9fa;">
                  <i class="bi bi-plus-lg me-1"></i>Add New Line
                </td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Salary Assignments saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/salary_assignments_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/human_resources_payroll/salary_setup/salary_assignments/salary_assignments.js"></script>