<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>

<!-- Report Info Modal -->
<div class="modal fade" id="reportInfoModal" tabindex="-1" aria-labelledby="reportInfoModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="reportInfoModalLabel">
          <i class="bi bi-info-circle me-2 text-primary"></i>About: Top Performing Drivers
        </h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">

        <h6 class="fw-bold text-primary mb-2"><i class="bi bi-bullseye me-1"></i>Purpose</h6>
        <p class="mb-3">
          The <strong>Top Performing Drivers</strong> report ranks drivers by the total revenue they generated within a
          selected period. It answers: <em>"Who are our highest-earning drivers and how productive are they?"</em> —
          supporting performance reviews, incentive planning, and workload distribution decisions.
        </p>

        <hr>

        <h6 class="fw-bold text-primary mb-2"><i class="bi bi-database me-1"></i>Database Structure</h6>
        <p class="mb-1">This report draws from the following tables:</p>
        <table class="table table-sm table-bordered mb-3">
          <thead class="table-light">
            <tr><th>Table</th><th>Column</th><th>Type</th><th>Role in this report</th></tr>
          </thead>
          <tbody>
            <tr><td><code>drivers</code></td><td><code>id, ref, name</code></td><td>INT / TEXT</td><td>Identifies each driver in the result</td></tr>
            <tr><td><code>trips</code></td><td><code>driver_id</code></td><td>INT (FK)</td><td>Links each trip to its driver</td></tr>
            <tr><td><code>trips</code></td><td><code>amount</code></td><td>NUMERIC</td><td>Revenue generated by the trip</td></tr>
            <tr><td><code>trips</code></td><td><code>damount</code></td><td>NUMERIC</td><td>Driver's commission/payment for the trip</td></tr>
            <tr><td><code>trips</code></td><td><code>day_pay</code></td><td>NUMERIC</td><td>Additional day pay component for the driver</td></tr>
            <tr><td><code>trips</code></td><td><code>date</code></td><td>DATE</td><td>Used to filter trips within the selected date range</td></tr>
          </tbody>
        </table>

        <hr>

        <h6 class="fw-bold text-primary mb-2"><i class="bi bi-gear me-1"></i>How Data Is Gathered</h6>
        <ol class="mb-3">
          <li class="mb-1"><strong>Filter by date range</strong> — All trips where <code>date</code> falls within the selected From–To period are fetched.</li>
          <li class="mb-1"><strong>Group by driver</strong> — Trips are grouped by <code>driver_id</code>; trips with no driver assigned are excluded.</li>
          <li class="mb-1"><strong>Aggregate per driver</strong> — Trip count is tallied, <code>amount</code> is summed as total revenue, and <code>damount + day_pay</code> is summed as total driver earnings.</li>
          <li class="mb-1"><strong>Calculate average</strong> — <code>avg_per_trip = total_revenue ÷ trip_count</code>.</li>
          <li class="mb-1"><strong>Sort &amp; rank</strong> — Drivers are sorted by total revenue descending and assigned ranks; the top-ranked driver's row is highlighted in gold.</li>
          <li class="mb-1"><strong>Apply limit</strong> — The "Top" filter (5, 10, or All) truncates the result after sorting.</li>
        </ol>

        <div class="alert alert-info mb-0 py-2">
          <i class="bi bi-lightbulb me-1"></i>
          <strong>Tip:</strong> Total Earning reflects only <code>damount</code> and <code>day_pay</code> from trips — it does not include salary, advances, or deductions recorded elsewhere.
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div id="top-driver-app">
  <div class="card mb-3">
    <div class="card-header d-flex align-items-center gap-3 flex-wrap">
      <strong class="me-auto">Top Performing Drivers</strong>
      <div class="d-flex align-items-center gap-2">
        <label class="mb-0 small">From</label>
        <input type="date" class="form-control form-control-sm" v-model="from" style="width:150px">
        <label class="mb-0 small">To</label>
        <input type="date" class="form-control form-control-sm" v-model="to" style="width:150px">
        <label class="mb-0 small">Top</label>
        <select class="form-select form-select-sm" v-model="limit" style="width:90px">
          <option value="5">5</option>
          <option value="10">10</option>
          <option value="all">All</option>
        </select>
        <button class="btn btn-primary btn-sm" @click="load" :disabled="loading">
          <span v-if="loading" class="spinner-border spinner-border-sm me-1"></span>Run
        </button>
        <div class="report-export-btns d-flex align-items-center gap-2">
          <button type="button" class="btn btn-sm btn-outline-success" onclick="ReportUtils.exportExcel()">
            <i class="bi bi-file-earmark-excel me-1"></i>Export Excel
          </button>
          <button type="button" class="btn btn-sm btn-outline-secondary" onclick="ReportUtils.printReport()">
            <i class="bi bi-printer me-1"></i>Print / PDF
          </button>
          <button type="button" class="btn btn-outline-secondary btn-sm" data-bs-toggle="modal" data-bs-target="#reportInfoModal" title="How this report works">
            <i class="bi bi-info-circle me-1"></i>How this report works
          </button>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div class="d-flex flex-wrap gap-1 align-items-center mb-2 pb-2 border-bottom">
        <small class="text-muted me-1">Jump to:</small>
        <button v-for="mn in months" :key="mn.month" type="button"
          class="btn btn-sm btn-outline-secondary"
          @click="selectMonth(mn.year, mn.month)">{{ mn.label }}</button>
      </div>
      <div v-if="error" class="alert alert-danger">{{ error }}</div>
      <div v-if="rows.length">
        <div id="topDriverChart" class="mb-3"></div>
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-sm align-middle">
            <thead class="table-dark">
              <tr>
                <th>Rank</th>
                <th>Ref</th>
                <th>Name</th>
                <th class="text-end">Trips</th>
                <th class="text-end">Total Revenue (LKR)</th>
                <th class="text-end">Total Earning (LKR)</th>
                <th class="text-end">Avg/Trip (LKR)</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="r in rows" :key="r.driver_id" :class="r.rank === 1 ? 'table-warning' : ''">
                <td class="fw-bold">{{ r.rank }}</td>
                <td>{{ r.ref }}</td>
                <td>{{ r.name }}</td>
                <td class="text-end">{{ r.trip_count }}</td>
                <td class="text-end">{{ fmt(r.total_revenue) }}</td>
                <td class="text-end">{{ fmt(r.total_earning) }}</td>
                <td class="text-end">{{ fmt(r.avg_per_trip) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div v-else-if="!loading && ran" class="text-muted text-center py-3">No data for the selected period.</div>
    </div>
  </div>
</div>
<script src="/modules/reports/analytics_reports/top_performing_driver/top_performing_driver.js"></script>
