<?php
require_once __DIR__ . '/../../../../server/supabase.php';

function supabase_get_print(string $path): array {
    $ch = curl_init(SUPABASE_URL . $path);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, ['apikey: '.SUPABASE_ANON_KEY,'Authorization: Bearer '.SUPABASE_ANON_KEY,'Accept: application/json']);
    $result = json_decode(curl_exec($ch), true) ?? [];
    return $result;
}

$company_rows = supabase_get_print(SB_API . 'sys_company_info?select=*&limit=1');
$company = $company_rows[0] ?? ['name' => 'Ones n Zeros', 'address' => '', 'phone' => '', 'email' => ''];

$ref            = htmlspecialchars($_GET['ref'] ?? '');
$cleaner_ref    = htmlspecialchars($_GET['cleaner_ref'] ?? '');
$cleaner_name   = htmlspecialchars($_GET['cleaner_name'] ?? '');
$month          = htmlspecialchars($_GET['month'] ?? '');
$gross_earnings = number_format(floatval($_GET['gross_earnings'] ?? 0), 2);
$advances       = number_format(floatval($_GET['advances'] ?? 0), 2);
$net_payable    = number_format(floatval($_GET['net_payable'] ?? 0), 2);
$status         = htmlspecialchars(strtoupper($_GET['status'] ?? ''));
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Cleaner Salary Settlement - <?= $ref ?></title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 13px; color: #222; background: #fff; padding: 30px; }
    .letterhead { text-align: center; border-bottom: 2px solid #333; padding-bottom: 14px; margin-bottom: 18px; }
    .letterhead h1 { font-size: 22px; font-weight: bold; margin-bottom: 4px; }
    .letterhead p { font-size: 12px; color: #555; }
    .doc-title { text-align: center; font-size: 17px; font-weight: bold; text-transform: uppercase;
                 letter-spacing: 1px; margin-bottom: 20px; text-decoration: underline; }
    table.details { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
    table.details th, table.details td { border: 1px solid #ccc; padding: 8px 12px; }
    table.details th { background: #f5f5f5; width: 40%; font-weight: 600; }
    table.details td.amount { text-align: right; font-family: monospace; font-size: 14px; }
    table.details td.net { font-weight: bold; color: #155724; font-size: 15px; text-align: right; font-family: monospace; }
    .signatures { display: flex; justify-content: space-between; margin-top: 60px; }
    .sig-box { width: 40%; text-align: center; }
    .sig-box .sig-line { border-top: 1px solid #555; padding-top: 6px; margin-top: 40px; font-size: 12px; color: #555; }
    .footer-note { margin-top: 30px; text-align: center; font-size: 11px; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }
    .print-buttons { text-align: center; margin-bottom: 20px; }
    .print-buttons button { margin: 0 6px; padding: 8px 20px; font-size: 14px; cursor: pointer; }
    .badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 12px; font-weight: bold; color: #fff; }
    .badge-pending { background: #ffc107; color: #333; }
    .badge-paid    { background: #198754; }
    @media print {
      .print-buttons { display: none; }
      body { padding: 15px; }
    }
  </style>
</head>
<body>

<div class="print-buttons">
  <button onclick="window.print()">&#128438; Print</button>
  <button onclick="window.close()">&#10006; Close</button>
</div>

<div class="letterhead">
  <h1><?= htmlspecialchars($company['name'] ?? 'Ones n Zeros') ?></h1>
  <p><?= htmlspecialchars($company['address'] ?? '') ?></p>
  <p>
    <?php if (!empty($company['phone'])): ?>Tel: <?= htmlspecialchars($company['phone']) ?><?php endif; ?>
    <?php if (!empty($company['email'])): ?> &nbsp;|&nbsp; Email: <?= htmlspecialchars($company['email']) ?><?php endif; ?>
  </p>
</div>

<div class="doc-title">Cleaner Salary Settlement</div>

<table class="details">
  <tr><th>Reference No.</th><td><?= $ref ?></td></tr>
  <tr><th>Cleaner Ref.</th><td><?= $cleaner_ref ?></td></tr>
  <tr><th>Cleaner Name</th><td><?= $cleaner_name ?></td></tr>
  <tr><th>Month</th><td><?= $month ?></td></tr>
  <tr><th>Status</th><td><span class="badge badge-<?= strtolower($_GET['status'] ?? 'pending') ?>"><?= $status ?></span></td></tr>
  <tr><th>Gross Earnings (LKR)</th><td class="amount"><?= $gross_earnings ?></td></tr>
  <tr><th>Advances (LKR)</th><td class="amount"><?= $advances ?></td></tr>
  <tr><th>Net Payable (LKR)</th><td class="net"><?= $net_payable ?></td></tr>
</table>

<div class="signatures">
  <div class="sig-box">
    <div class="sig-line">Prepared By</div>
  </div>
  <div class="sig-box">
    <div class="sig-line">Authorized By</div>
  </div>
</div>

<div class="footer-note">
  Generated by Ones n Zeros ERP &mdash; <?= date('Y-m-d H:i') ?>
</div>

</body>
</html>
