// leave_management.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      employee_ref: '',
      employee_name: '',
      leave_type: '',
      start_date: '',
      end_date: '',
      leave_status: '',
      reason: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.employee_ref !== '' ||
        this.form.leave_type !== '' ||
        this.form.start_date !== '' ||
        this.form.end_date !== '' ||
        this.form.leave_status !== '' ||
        this.form.reason !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('leave_management-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('lm-employee-selected', (e) => {
      this.form.employee_ref  = e.detail.ref;
      this.form.employee_name = e.detail.full_name;
    });
  },

  methods: {
    clearEmployee() { this.form.employee_ref = ''; this.form.employee_name = ''; },

    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/human_resources_payroll/hr_operations/leave_management/leave_management_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        employee_name: String(this.form.employee_name ?? ''),
        leave_type: String(this.form.leave_type ?? ''),
        start_date: String(this.form.start_date ?? ''),
        end_date: String(this.form.end_date ?? ''),
        leave_status: String(this.form.leave_status ?? ''),
        reason: String(this.form.reason ?? ''),
          });
          window.open('/modules/human_resources_payroll/hr_operations/leave_management/leave_management_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.employee_ref = '';
      this.form.employee_name = '';
      this.form.leave_type = '';
      this.form.start_date = '';
      this.form.end_date = '';
      this.form.leave_status = '';
      this.form.reason = '';
    },

    onSave() {
      if (!this.isDirty) return;
      if (!this.form.employee_ref) { this.error = 'Please select an Employee.'; return; }
      if (this.$refs.form && !this.$refs.form.reportValidity()) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/human_resources_payroll/hr_operations/leave_management/leave_management_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = err.response?.data?.error || 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/human_resources_payroll/hr_operations/leave_management/leave_management_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.employee_ref = data.employee_ref ?? '';
      this.form.employee_name = data.m_employees?.full_name ?? data.employee_ref ?? '';
      this.form.leave_type = data.leave_type;
      this.form.start_date = data.start_date;
      this.form.end_date = data.end_date;
      this.form.leave_status = data.leave_status;
      this.form.reason = data.reason;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#leave-management-app');