<?php
// leave_management_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveLeaveManagement(array $data): array {
    $ref = consumeNextReference('leave_management');

    $record = supabase_post(SB_API . 'm_leave_requests', [
        'ref' => $ref,
        'employee_ref' => !empty($data['employee_ref']) ? $data['employee_ref'] : null,
        'leave_type' => $data['leave_type'] ?? '',
        'start_date' => !empty($data['start_date']) ? $data['start_date'] : null,
        'end_date' => !empty($data['end_date']) ? $data['end_date'] : null,
        'leave_status' => $data['leave_status'] ?? '',
        'reason' => $data['reason'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateLeaveManagement(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_leave_requests', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_leave_requests?ref=eq.' . urlencode($ref), [
        'employee_ref' => !empty($data['employee_ref']) ? $data['employee_ref'] : null,
        'leave_type' => $data['leave_type'] ?? '',
        'start_date' => !empty($data['start_date']) ? $data['start_date'] : null,
        'end_date' => !empty($data['end_date']) ? $data['end_date'] : null,
        'leave_status' => $data['leave_status'] ?? '',
        'reason' => $data['reason'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listLeaveManagement(): array {
    return supabase_get(SB_API . 'm_leave_requests?select=id,ref,employee_ref,leave_type,start_date,end_date,leave_status,reason,m_employees(full_name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listLeaveManagement());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveLeaveManagement($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateLeaveManagement($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_leave_requests', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}