<?php /* modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master.php — generated by Generate Module */ ?>

<div id="freelance-crew-master-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#freelanceCrewMasterSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="freelance-crew-master-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="freelance-crew-master-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <form ref="form">
    <div class="row mb-3">
      <label for="freelance-crew-master-full-name" class="col-sm-4 col-form-label">Full Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="freelance-crew-master-full-name" v-model="form.full_name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="freelance-crew-master-role-type" class="col-sm-4 col-form-label">Role Type</label>
      <div class="col-sm-8">
        <select class="form-select" id="freelance-crew-master-role-type" v-model="form.role_type" required>
                  <option value="" disabled>Select…</option>
                  <option value="Usher">Usher</option>
                  <option value="Setup Staff">Setup Staff</option>
                  <option value="Ground Staff">Ground Staff</option>
                  <option value="Floral Assistant">Floral Assistant</option>
                  <option value="Other">Other</option>
                </select>
      </div>
    </div>
    <div class="row mb-3">
      <label for="freelance-crew-master-phone" class="col-sm-4 col-form-label">Phone</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="freelance-crew-master-phone" v-model="form.phone" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="freelance-crew-master-nic" class="col-sm-4 col-form-label">NIC</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="freelance-crew-master-nic" v-model="form.nic" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="freelance-crew-master-daily-rate" class="col-sm-4 col-form-label">Daily Rate</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="freelance-crew-master-daily-rate" v-model.number="form.daily_rate" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="freelance-crew-master-notes" class="col-sm-4 col-form-label">Notes</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="freelance-crew-master-notes" v-model="form.notes"></textarea>
      </div>
    </div>
    </form>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Freelance Crew Master saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/freelance_crew_master_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master.js"></script>