<?php
// freelance_crew_master_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveFreelanceCrewMaster(array $data): array {
    $ref = consumeNextReference('freelance_crew_master');

    $record = supabase_post(SB_API . 'm_freelance_crew', [
        'ref' => $ref,
        'full_name' => $data['full_name'] ?? '',
        'role_type' => $data['role_type'] ?? '',
        'phone' => $data['phone'] ?? '',
        'nic' => $data['nic'] ?? '',
        'daily_rate' => $data['daily_rate'] ?? 0,
        'notes' => $data['notes'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);

    return $record;
}

function updateFreelanceCrewMaster(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_freelance_crew', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_freelance_crew?ref=eq.' . urlencode($ref), [
        'full_name' => $data['full_name'] ?? '',
        'role_type' => $data['role_type'] ?? '',
        'phone' => $data['phone'] ?? '',
        'nic' => $data['nic'] ?? '',
        'daily_rate' => $data['daily_rate'] ?? 0,
        'notes' => $data['notes'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listFreelanceCrewMaster(): array {
    return supabase_get(SB_API . 'm_freelance_crew?select=id,ref,full_name,role_type,phone,nic,daily_rate,notes&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listFreelanceCrewMaster());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveFreelanceCrewMaster($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateFreelanceCrewMaster($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_freelance_crew', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}