// freelance_crew_master_search.js — generated by Generate Module

$(document).ready(function () {

  const table = $('#freelanceCrewMasterSearchTable').DataTable({
    ajax: { url: '/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'full_name' },
      { data: 'role_type' },
      { data: 'phone' },
      { data: 'nic' },
      { data: 'daily_rate' },
      { data: 'notes' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Freelance Crew Master records',
    },
  });

  $('#freelanceCrewMasterSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('freelanceCrewMasterSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('freelance_crew_master-selected', { detail: data }));
  });
  $('#freelanceCrewMasterSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});