// freelance_crew_master.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      full_name: '',
      role_type: '',
      phone: '',
      nic: '',
      daily_rate: 0,
      notes: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.full_name !== '' ||
        this.form.role_type !== '' ||
        this.form.phone !== '' ||
        this.form.nic !== '' ||
        this.form.daily_rate !== 0 ||
        this.form.notes !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('freelance_crew_master-selected', (e) => this.loadRecord(e.detail));
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        full_name: String(this.form.full_name ?? ''),
        role_type: String(this.form.role_type ?? ''),
        phone: String(this.form.phone ?? ''),
        nic: String(this.form.nic ?? ''),
        daily_rate: String(this.form.daily_rate ?? ''),
        notes: String(this.form.notes ?? ''),
          });
          window.open('/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.full_name = '';
      this.form.role_type = '';
      this.form.phone = '';
      this.form.nic = '';
      this.form.daily_rate = 0;
      this.form.notes = '';
    },

    onSave() {
      if (!this.isDirty) return;
      if (this.$refs.form && !this.$refs.form.reportValidity()) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = err.response?.data?.error || 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/staff_fleet/freelance_crew_master/freelance_crew_master_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.full_name = data.full_name;
      this.form.role_type = data.role_type;
      this.form.phone = data.phone;
      this.form.nic = data.nic;
      this.form.daily_rate = data.daily_rate;
      this.form.notes = data.notes;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#freelance-crew-master-app');