<?php
// gps_device_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveGpsDevice(array $data): array {
    $ref = consumeNextReference('gps_device');

    return supabase_post(SB_API . 'm_gps_devices', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'serial_number' => $data['serial_number'] ?? '',
        'imei' => $data['imei'] ?? '',
        'sim_number' => $data['sim_number'] ?? '',
        'manufacturer' => $data['manufacturer'] ?? '',
        'model' => $data['model'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateGpsDevice(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_gps_devices', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_gps_devices?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'serial_number' => $data['serial_number'] ?? '',
        'imei' => $data['imei'] ?? '',
        'sim_number' => $data['sim_number'] ?? '',
        'manufacturer' => $data['manufacturer'] ?? '',
        'model' => $data['model'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listGpsDevice(): array {
    return supabase_get(SB_API . 'm_gps_devices?select=id,ref,code,serial_number,imei,sim_number,manufacturer,model&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listGpsDevice());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveGpsDevice($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateGpsDevice($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_gps_devices', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}