// gps_device.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      code: '',
      serial_number: '',
      imei: '',
      sim_number: '',
      manufacturer: '',
      model: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.code !== '' ||
        this.form.serial_number !== '' ||
        this.form.imei !== '' ||
        this.form.sim_number !== '' ||
        this.form.manufacturer !== '' ||
        this.form.model !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('gps_device-selected', (e) => this.loadRecord(e.detail));
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/vehicle/gps_device/gps_device_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        code: String(this.form.code ?? ''),
        serial_number: String(this.form.serial_number ?? ''),
        imei: String(this.form.imei ?? ''),
        sim_number: String(this.form.sim_number ?? ''),
        manufacturer: String(this.form.manufacturer ?? ''),
        model: String(this.form.model ?? ''),
          });
          window.open('/modules/master_files/vehicle/gps_device/gps_device_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.code = '';
      this.form.serial_number = '';
      this.form.imei = '';
      this.form.sim_number = '';
      this.form.manufacturer = '';
      this.form.model = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/vehicle/gps_device/gps_device_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/vehicle/gps_device/gps_device_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.code = data.code;
      this.form.serial_number = data.serial_number;
      this.form.imei = data.imei;
      this.form.sim_number = data.sim_number;
      this.form.manufacturer = data.manufacturer;
      this.form.model = data.model;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#gps-device-app');