<?php /* modules/master_files/vehicle/gps_device/gps_device.php — generated by Generate Module */ ?>

<div id="gps-device-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#gpsDeviceSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="gps-device-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="gps-device-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
            <div class="row mb-3">
      <label for="gps-device-code" class="col-sm-4 col-form-label">Code</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="gps-device-code" v-model="form.code" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="gps-device-serial-number" class="col-sm-4 col-form-label">Serial Number</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="gps-device-serial-number" v-model="form.serial_number" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="gps-device-imei" class="col-sm-4 col-form-label">IMEI</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="gps-device-imei" v-model="form.imei" />
      </div>
    </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label for="gps-device-sim-number" class="col-sm-4 col-form-label">SIM Number</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="gps-device-sim-number" v-model="form.sim_number" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="gps-device-manufacturer" class="col-sm-4 col-form-label">Manufacturer</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="gps-device-manufacturer" v-model="form.manufacturer" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="gps-device-model" class="col-sm-4 col-form-label">Model</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="gps-device-model" v-model="form.model" />
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Gps Device saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/gps_device_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/vehicle/gps_device/gps_device.js"></script>