// employment_record.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      employee_ref: '',
      employee_name: '',
      employment_type_ref: '',
      employment_type_name: '',
      payroll_profile_ref: '',
      payroll_profile_name: '',
      joining_date: '',
      confirmation_date: '',
      termination_date: '',
      employment_status: '',
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.employee_ref !== '' ||
        this.form.employment_type_ref !== '' ||
        this.form.payroll_profile_ref !== '' ||
        this.form.joining_date !== '' ||
        this.form.confirmation_date !== '' ||
        this.form.termination_date !== '' ||
        this.form.employment_status !== '' ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('employment_record-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('er-employee-selected', (e) => {
      this.form.employee_ref  = e.detail.ref;
      this.form.employee_name = e.detail.full_name;
    });
    document.addEventListener('er-employment-type-selected', (e) => {
      this.form.employment_type_ref  = e.detail.ref;
      this.form.employment_type_name = e.detail.name;
    });
    document.addEventListener('er-payroll-profile-selected', (e) => {
      this.form.payroll_profile_ref  = e.detail.ref;
      this.form.payroll_profile_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearEmployee()       { this.form.employee_ref = '';        this.form.employee_name = ''; },
    clearEmploymentType() { this.form.employment_type_ref = ''; this.form.employment_type_name = ''; },
    clearPayrollProfile() { this.form.payroll_profile_ref = ''; this.form.payroll_profile_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/people/employment_record/employment_record_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        employee_name: String(this.form.employee_name ?? ''),
        employment_type_name: String(this.form.employment_type_name ?? ''),
        payroll_profile_name: String(this.form.payroll_profile_name ?? ''),
        joining_date: String(this.form.joining_date ?? ''),
        confirmation_date: String(this.form.confirmation_date ?? ''),
        termination_date: String(this.form.termination_date ?? ''),
        employment_status: String(this.form.employment_status ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/master_files/people/employment_record/employment_record_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.employee_ref = '';
      this.form.employee_name = '';
      this.form.employment_type_ref = '';
      this.form.employment_type_name = '';
      this.form.payroll_profile_ref = '';
      this.form.payroll_profile_name = '';
      this.form.joining_date = '';
      this.form.confirmation_date = '';
      this.form.termination_date = '';
      this.form.employment_status = '';
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/people/employment_record/employment_record_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/people/employment_record/employment_record_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.employee_ref = data.employee_ref ?? '';
      this.form.employee_name = data.m_employees?.full_name ?? '';
      this.form.employment_type_ref = data.employment_type_ref ?? '';
      this.form.employment_type_name = data.m_employment_types?.name ?? '';
      this.form.payroll_profile_ref = data.payroll_profile_ref ?? '';
      this.form.payroll_profile_name = data.m_payroll_profiles?.name ?? '';
      this.form.joining_date = data.joining_date;
      this.form.confirmation_date = data.confirmation_date;
      this.form.termination_date = data.termination_date;
      this.form.employment_status = data.employment_status;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#employment-record-app');