// employment_record_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Employee picker ──────────────────────────────────────────────────────
  const employeePicker = $('#erEmployeePickerTable').DataTable({
    ajax: { url: '/modules/master_files/people/employee_master/employee_master_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'full_name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#erEmployeePickerTable tbody').on('click', 'tr', function () {
    const data = employeePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('erEmployeePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('er-employee-selected', { detail: data }));
  });

  $('#erEmployeePickerModal').on('shown.bs.modal', function () {
    employeePicker.ajax.reload(null, false);
    employeePicker.columns.adjust();
  });

  // ── Employment Type picker ───────────────────────────────────────────────
  const employmentTypePicker = $('#erEmploymentTypePickerTable').DataTable({
    ajax: { url: '/modules/master_files/organisation/employment_types/employment_types_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#erEmploymentTypePickerTable tbody').on('click', 'tr', function () {
    const data = employmentTypePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('erEmploymentTypePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('er-employment-type-selected', { detail: data }));
  });

  $('#erEmploymentTypePickerModal').on('shown.bs.modal', function () {
    employmentTypePicker.ajax.reload(null, false);
    employmentTypePicker.columns.adjust();
  });

  // ── Payroll Profile picker ───────────────────────────────────────────────
  const payrollProfilePicker = $('#erPayrollProfilePickerTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/salary_setup/payroll_profiles/payroll_profiles_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#erPayrollProfilePickerTable tbody').on('click', 'tr', function () {
    const data = payrollProfilePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('erPayrollProfilePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('er-payroll-profile-selected', { detail: data }));
  });

  $('#erPayrollProfilePickerModal').on('shown.bs.modal', function () {
    payrollProfilePicker.ajax.reload(null, false);
    payrollProfilePicker.columns.adjust();
  });

  const table = $('#employmentRecordSearchTable').DataTable({
    ajax: { url: '/modules/master_files/people/employment_record/employment_record_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_employees.full_name', defaultContent: '' },
      { data: 'm_employment_types.name', defaultContent: '' },
      { data: 'm_payroll_profiles.name', defaultContent: '' },
      { data: 'joining_date' },
      { data: 'confirmation_date' },
      { data: 'termination_date' },
      { data: 'employment_status' },
      { data: 'remarks' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Employment Record records',
    },
  });

  $('#employmentRecordSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('employmentRecordSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('employment_record-selected', { detail: data }));
  });

  $('#employmentRecordSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});