<?php
// employment_record_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveEmploymentRecord(array $data): array {
    $ref = consumeNextReference('employment_record');

    return supabase_post(SB_API . 'm_employment_records', [
        'ref' => $ref,
        'employee_ref' => !empty($data['employee_ref']) ? $data['employee_ref'] : null,
        'employment_type_ref' => !empty($data['employment_type_ref']) ? $data['employment_type_ref'] : null,
        'payroll_profile_ref' => !empty($data['payroll_profile_ref']) ? $data['payroll_profile_ref'] : null,
        'joining_date' => !empty($data['joining_date']) ? $data['joining_date'] : null,
        'confirmation_date' => !empty($data['confirmation_date']) ? $data['confirmation_date'] : null,
        'termination_date' => !empty($data['termination_date']) ? $data['termination_date'] : null,
        'employment_status' => $data['employment_status'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateEmploymentRecord(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_employment_records', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_employment_records?ref=eq.' . urlencode($ref), [
        'employee_ref' => !empty($data['employee_ref']) ? $data['employee_ref'] : null,
        'employment_type_ref' => !empty($data['employment_type_ref']) ? $data['employment_type_ref'] : null,
        'payroll_profile_ref' => !empty($data['payroll_profile_ref']) ? $data['payroll_profile_ref'] : null,
        'joining_date' => !empty($data['joining_date']) ? $data['joining_date'] : null,
        'confirmation_date' => !empty($data['confirmation_date']) ? $data['confirmation_date'] : null,
        'termination_date' => !empty($data['termination_date']) ? $data['termination_date'] : null,
        'employment_status' => $data['employment_status'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listEmploymentRecord(): array {
    return supabase_get(SB_API . 'm_employment_records?select=id,ref,employee_ref,employment_type_ref,payroll_profile_ref,joining_date,confirmation_date,termination_date,employment_status,remarks,m_employees(full_name),m_employment_types(name),m_payroll_profiles(name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listEmploymentRecord());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveEmploymentRecord($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateEmploymentRecord($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_employment_records', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}