<?php /* modules/operations/fleet_maintenance/vehicle_gps/vehicle_gps.php — generated by Generate Module */ ?>

<div id="vehicle-gps-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#vehicleGpsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="vehicle-gps-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="vehicle-gps-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
            <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Vehicle</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-gps-vehicle-ref" v-model="form.vehicle_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.vehicle_plate" placeholder="Plate number…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vgpVehiclePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearVehicle" v-if="form.vehicle_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">GPS Device</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-gps-gps-device-ref" v-model="form.gps_device_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.gps_device_code" placeholder="Device code…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vgpGpsDevicePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearGpsDevice" v-if="form.gps_device_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label for="vehicle-gps-installed-date" class="col-sm-4 col-form-label">Installed Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="vehicle-gps-installed-date" v-model="form.installed_date" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-gps-removed-date" class="col-sm-4 col-form-label">Removed Date</label>
      <div class="col-sm-8">
        <input type="date" class="form-control" id="vehicle-gps-removed-date" v-model="form.removed_date" />
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Vehicle Gps saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/vehicle_gps_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/operations/fleet_maintenance/vehicle_gps/vehicle_gps.js"></script>