<?php
// work_order_types_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveWorkOrderTypes(array $data): array {
    $ref = consumeNextReference('work_order_types');

    return supabase_post(SB_API . 'm_work_order_types', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'requires_customer' => $data['requires_customer'] ?? false,
        'uses_vehicle' => $data['uses_vehicle'] ?? false,
        'uses_driver' => $data['uses_driver'] ?? false,
        'is_billable' => $data['is_billable'] ?? false,
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateWorkOrderTypes(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_work_order_types', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_work_order_types?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'requires_customer' => $data['requires_customer'] ?? false,
        'uses_vehicle' => $data['uses_vehicle'] ?? false,
        'uses_driver' => $data['uses_driver'] ?? false,
        'is_billable' => $data['is_billable'] ?? false,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listWorkOrderTypes(): array {
    return supabase_get(SB_API . 'm_work_order_types?select=id,ref,code,name,description,requires_customer,uses_vehicle,uses_driver,is_billable&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listWorkOrderTypes());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveWorkOrderTypes($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateWorkOrderTypes($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_work_order_types', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}