<?php /* modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs.php — generated by Generate Module */ ?>

<div id="payroll-inputs-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#payrollInputsSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="payroll-inputs-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="payroll-inputs-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Employment Record</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="payroll-inputs-employment-record-ref" v-model="form.employment_record_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.employment_record_name" placeholder="Employment record…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#piEmploymentRecordPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearEmploymentRecord" v-if="form.employment_record_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Payroll Period</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="payroll-inputs-payroll-period-ref" v-model="form.payroll_period_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.payroll_period_name" placeholder="Payroll period…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#piPayrollPeriodPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearPayrollPeriod" v-if="form.payroll_period_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Salary Component</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="payroll-inputs-salary-component-ref" v-model="form.salary_component_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.salary_component_name" placeholder="Salary component…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#piSalaryComponentPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearSalaryComponent" v-if="form.salary_component_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-quantity" class="col-sm-4 col-form-label">Quantity</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-inputs-quantity" v-model.number="form.quantity" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-rate" class="col-sm-4 col-form-label">Rate</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-inputs-rate" v-model.number="form.rate" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-amount" class="col-sm-4 col-form-label">Amount</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="payroll-inputs-amount" v-model.number="form.amount" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-source-type" class="col-sm-4 col-form-label">Source Type</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="payroll-inputs-source-type" v-model="form.source_type" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-source-ref" class="col-sm-4 col-form-label">Source Ref</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="payroll-inputs-source-ref" v-model="form.source_ref" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-remarks" class="col-sm-4 col-form-label">Remarks</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="payroll-inputs-remarks" v-model="form.remarks"></textarea>
      </div>
    </div>
    <div class="row mb-3">
      <label for="payroll-inputs-approval-status" class="col-sm-4 col-form-label">Approval Status</label>
      <div class="col-sm-8">
        <select class="form-select" id="payroll-inputs-approval-status" v-model="form.approval_status" required>
                  <option value="" disabled>Select…</option>
                  <option value="Pending">Pending</option>
                  <option value="Approved">Approved</option>
                  <option value="Rejected">Rejected</option>
                </select>
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Payroll Inputs saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/payroll_inputs_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs.js"></script>