// payroll_inputs_search.js — generated by Generate Module

$(document).ready(function () {

  // ── Employment Record picker ─────────────────────────────────────────────
  const employmentRecordPicker = $('#piEmploymentRecordPickerTable').DataTable({
    ajax: { url: '/modules/master_files/people/employment_record/employment_record_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_employees.full_name', defaultContent: '' },
      { data: 'm_employment_types.name', defaultContent: '' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#piEmploymentRecordPickerTable tbody').on('click', 'tr', function () {
    const data = employmentRecordPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('piEmploymentRecordPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('pi-employment-record-selected', { detail: data }));
  });

  $('#piEmploymentRecordPickerModal').on('shown.bs.modal', function () {
    employmentRecordPicker.ajax.reload(null, false);
    employmentRecordPicker.columns.adjust();
  });

  // ── Payroll Period picker ────────────────────────────────────────────────
  const payrollPeriodPicker = $('#piPayrollPeriodPickerTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/payroll_processing/payroll_periods/payroll_periods_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#piPayrollPeriodPickerTable tbody').on('click', 'tr', function () {
    const data = payrollPeriodPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('piPayrollPeriodPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('pi-payroll-period-selected', { detail: data }));
  });

  $('#piPayrollPeriodPickerModal').on('shown.bs.modal', function () {
    payrollPeriodPicker.ajax.reload(null, false);
    payrollPeriodPicker.columns.adjust();
  });

  // ── Salary Component picker ──────────────────────────────────────────────
  const salaryComponentPicker = $('#piSalaryComponentPickerTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/salary_setup/salary_components/salary_components_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#piSalaryComponentPickerTable tbody').on('click', 'tr', function () {
    const data = salaryComponentPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('piSalaryComponentPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('pi-salary-component-selected', { detail: data }));
  });

  $('#piSalaryComponentPickerModal').on('shown.bs.modal', function () {
    salaryComponentPicker.ajax.reload(null, false);
    salaryComponentPicker.columns.adjust();
  });

  const table = $('#payrollInputsSearchTable').DataTable({
    ajax: { url: '/modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'm_employment_records.m_employees.full_name', defaultContent: '' },
      { data: 'm_payroll_periods.name', defaultContent: '' },
      { data: 'm_salary_components.name', defaultContent: '' },
      { data: 'quantity' },
      { data: 'rate' },
      { data: 'amount' },
      { data: 'source_type' },
      { data: 'source_ref' },
      { data: 'remarks' },
      { data: 'approval_status' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Payroll Inputs records',
    },
  });

  $('#payrollInputsSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('payrollInputsSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('payroll_inputs-selected', { detail: data }));
  });

  $('#payrollInputsSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});