<?php
// payroll_inputs_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function savePayrollInputs(array $data): array {
    $ref = consumeNextReference('payroll_inputs');

    return supabase_post(SB_API . 'm_payroll_inputs', [
        'ref' => $ref,
        'employment_record_ref' => !empty($data['employment_record_ref']) ? $data['employment_record_ref'] : null,
        'payroll_period_ref' => !empty($data['payroll_period_ref']) ? $data['payroll_period_ref'] : null,
        'salary_component_ref' => !empty($data['salary_component_ref']) ? $data['salary_component_ref'] : null,
        'quantity' => $data['quantity'] ?? 0,
        'rate' => $data['rate'] ?? 0,
        'amount' => $data['amount'] ?? 0,
        'source_type' => $data['source_type'] ?? '',
        'source_ref' => $data['source_ref'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'approval_status' => $data['approval_status'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updatePayrollInputs(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_payroll_inputs', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_payroll_inputs?ref=eq.' . urlencode($ref), [
        'employment_record_ref' => !empty($data['employment_record_ref']) ? $data['employment_record_ref'] : null,
        'payroll_period_ref' => !empty($data['payroll_period_ref']) ? $data['payroll_period_ref'] : null,
        'salary_component_ref' => !empty($data['salary_component_ref']) ? $data['salary_component_ref'] : null,
        'quantity' => $data['quantity'] ?? 0,
        'rate' => $data['rate'] ?? 0,
        'amount' => $data['amount'] ?? 0,
        'source_type' => $data['source_type'] ?? '',
        'source_ref' => $data['source_ref'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'approval_status' => $data['approval_status'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listPayrollInputs(): array {
    return supabase_get(SB_API . 'm_payroll_inputs?select=id,ref,employment_record_ref,payroll_period_ref,salary_component_ref,quantity,rate,amount,source_type,source_ref,remarks,approval_status,m_employment_records(ref,m_employees(full_name)),m_payroll_periods(name),m_salary_components(name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listPayrollInputs());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(savePayrollInputs($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updatePayrollInputs($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_payroll_inputs', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}