// payroll_inputs.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      employment_record_ref: '',
      employment_record_name: '',
      payroll_period_ref: '',
      payroll_period_name: '',
      salary_component_ref: '',
      salary_component_name: '',
      quantity: 0,
      rate: 0,
      amount: 0,
      source_type: '',
      source_ref: '',
      remarks: '',
      approval_status: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.employment_record_ref !== '' ||
        this.form.payroll_period_ref !== '' ||
        this.form.salary_component_ref !== '' ||
        this.form.quantity !== 0 ||
        this.form.rate !== 0 ||
        this.form.amount !== 0 ||
        this.form.source_type !== '' ||
        this.form.source_ref !== '' ||
        this.form.remarks !== '' ||
        this.form.approval_status !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('payroll_inputs-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('pi-employment-record-selected', (e) => {
      this.form.employment_record_ref  = e.detail.ref;
      this.form.employment_record_name = e.detail.m_employees?.full_name ?? e.detail.ref;
    });
    document.addEventListener('pi-payroll-period-selected', (e) => {
      this.form.payroll_period_ref  = e.detail.ref;
      this.form.payroll_period_name = e.detail.name;
    });
    document.addEventListener('pi-salary-component-selected', (e) => {
      this.form.salary_component_ref  = e.detail.ref;
      this.form.salary_component_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearEmploymentRecord() { this.form.employment_record_ref = ''; this.form.employment_record_name = ''; },
    clearPayrollPeriod()   { this.form.payroll_period_ref = '';  this.form.payroll_period_name = ''; },
    clearSalaryComponent() { this.form.salary_component_ref = ''; this.form.salary_component_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        employment_record_name: String(this.form.employment_record_name ?? ''),
        payroll_period_name: String(this.form.payroll_period_name ?? ''),
        salary_component_name: String(this.form.salary_component_name ?? ''),
        quantity: String(this.form.quantity ?? ''),
        rate: String(this.form.rate ?? ''),
        amount: String(this.form.amount ?? ''),
        source_type: String(this.form.source_type ?? ''),
        source_ref: String(this.form.source_ref ?? ''),
        remarks: String(this.form.remarks ?? ''),
        approval_status: String(this.form.approval_status ?? ''),
          });
          window.open('/modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.employment_record_ref = '';
      this.form.employment_record_name = '';
      this.form.payroll_period_ref = '';
      this.form.payroll_period_name = '';
      this.form.salary_component_ref = '';
      this.form.salary_component_name = '';
      this.form.quantity = 0;
      this.form.rate = 0;
      this.form.amount = 0;
      this.form.source_type = '';
      this.form.source_ref = '';
      this.form.remarks = '';
      this.form.approval_status = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/human_resources_payroll/payroll_processing/payroll_inputs/payroll_inputs_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.employment_record_ref = data.employment_record_ref ?? '';
      this.form.employment_record_name = data.m_employment_records?.m_employees?.full_name ?? '';
      this.form.payroll_period_ref = data.payroll_period_ref ?? '';
      this.form.payroll_period_name = data.m_payroll_periods?.name ?? '';
      this.form.salary_component_ref = data.salary_component_ref ?? '';
      this.form.salary_component_name = data.m_salary_components?.name ?? '';
      this.form.quantity = data.quantity;
      this.form.rate = data.rate;
      this.form.amount = data.amount;
      this.form.source_type = data.source_type;
      this.form.source_ref = data.source_ref;
      this.form.remarks = data.remarks;
      this.form.approval_status = data.approval_status;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#payroll-inputs-app');