<?php
// fleet_statuses_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveFleetStatuses(array $data): array {
    $ref = consumeNextReference('fleet_statuses');

    return supabase_post(SB_API . 'm_fleet_statuses', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'is_operational' => $data['is_operational'] ?? false,
        'sort_order' => $data['sort_order'] ?? 0,
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateFleetStatuses(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_fleet_statuses', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_fleet_statuses?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'name' => $data['name'] ?? '',
        'description' => $data['description'] ?? '',
        'is_operational' => $data['is_operational'] ?? false,
        'sort_order' => $data['sort_order'] ?? 0,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listFleetStatuses(): array {
    return supabase_get(SB_API . 'm_fleet_statuses?select=id,ref,code,name,description,is_operational,sort_order&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listFleetStatuses());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveFleetStatuses($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateFleetStatuses($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_fleet_statuses', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}