<?php /* modules/master_files/vehicle/fleet_statuses/fleet_statuses.php — generated by Generate Module */ ?>

<div id="fleet-statuses-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#fleetStatusesSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="fleet-statuses-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="fleet-statuses-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label for="fleet-statuses-code" class="col-sm-4 col-form-label">Code</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="fleet-statuses-code" v-model="form.code" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="fleet-statuses-name" class="col-sm-4 col-form-label">Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="fleet-statuses-name" v-model="form.name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="fleet-statuses-description" class="col-sm-4 col-form-label">Description</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="fleet-statuses-description" v-model="form.description"></textarea>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-sm-8 offset-sm-4">
        <div class="form-check">
          <input class="form-check-input" type="checkbox" id="fleet-statuses-is-operational" v-model="form.is_operational" />
          <label class="form-check-label" for="fleet-statuses-is-operational">Is Operational</label>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="fleet-statuses-sort-order" class="col-sm-4 col-form-label">Sort Order</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="fleet-statuses-sort-order" v-model.number="form.sort_order" />
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Fleet Statuses saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/fleet_statuses_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/vehicle/fleet_statuses/fleet_statuses.js"></script>