// vehicle_model_search.js — generated by Generate Module

$(document).ready(function () {

  const statusBadge = function (data) {
    const c = { active: 'success', inactive: 'danger' };
    return '<span class="badge text-bg-' + (c[data] || 'secondary') + '">' + data + '</span>';
  };

  // ── Brand picker ─────────────────────────────────────────────────────────
  const brandPicker = $('#vmBrandPickerTable').DataTable({
    ajax: { url: '/modules/master_files/vehicle/vehicle_brand/vehicle_brand_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
      { data: 'country', defaultContent: '' },
      { data: 'status', render: statusBadge },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#vmBrandPickerTable tbody').on('click', 'tr', function () {
    const data = brandPicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('vmBrandPickerModal')).hide();
    document.dispatchEvent(new CustomEvent('vm-brand-selected', { detail: data }));
  });

  $('#vmBrandPickerModal').on('shown.bs.modal', function () {
    brandPicker.ajax.reload(null, false);
    brandPicker.columns.adjust();
  });

  // ── Vehicle Type picker ──────────────────────────────────────────────────
  const vehicleTypePicker = $('#vmVehicleTypePickerTable').DataTable({
    ajax: { url: '/modules/master_files/vehicle/vehicle_type/vehicle_type_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
      { data: 'status', render: statusBadge },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#vmVehicleTypePickerTable tbody').on('click', 'tr', function () {
    const data = vehicleTypePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('vmVehicleTypePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('vm-vehicle-type-selected', { detail: data }));
  });

  $('#vmVehicleTypePickerModal').on('shown.bs.modal', function () {
    vehicleTypePicker.ajax.reload(null, false);
    vehicleTypePicker.columns.adjust();
  });

  // ── Fuel Type picker ─────────────────────────────────────────────────────
  const fuelTypePicker = $('#vmFuelTypePickerTable').DataTable({
    ajax: { url: '/modules/master_files/vehicle/fuel_type/fuel_type_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'name' },
      { data: 'status', render: statusBadge },
    ],
    pageLength: 10,
    searching: true,
    dom: '<"d-flex justify-content-between align-items-center mb-2"f>rtip',
    language: { search: 'Filter:', info: 'Showing _START_ to _END_ of _TOTAL_' },
  });

  $('#vmFuelTypePickerTable tbody').on('click', 'tr', function () {
    const data = fuelTypePicker.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('vmFuelTypePickerModal')).hide();
    document.dispatchEvent(new CustomEvent('vm-fuel-type-selected', { detail: data }));
  });

  $('#vmFuelTypePickerModal').on('shown.bs.modal', function () {
    fuelTypePicker.ajax.reload(null, false);
    fuelTypePicker.columns.adjust();
  });

  const table = $('#vehicleModelSearchTable').DataTable({
    ajax: { url: '/modules/master_files/vehicle/vehicle_model/vehicle_model_data.php?action=list', dataSrc: '' },
    columns: [
      { data: 'ref' },
      { data: 'code' },
      { data: 'model_name' },
      { data: 'm_vehicle_brands.name', defaultContent: '' },
      { data: 'm_vehicle_types.name', defaultContent: '' },
      { data: 'm_fuel_types.name', defaultContent: '' },
      { data: 'manufacture_start_year' },
      { data: 'manufacture_end_year' },
      { data: 'axle_count' },
      { data: 'seating_capacity' },
      { data: 'payload_capacity_kg' },
      { data: 'volume_capacity_m3' },
      { data: 'fuel_tank_capacity_l' },
      { data: 'average_fuel_consumption' },
      { data: 'description' },
    ],
    pageLength: 10,
    lengthMenu: [5, 10, 25, 50],
    dom: '<"d-flex justify-content-between align-items-center mb-2"Bf>rtip',
    buttons: [
      { extend: 'copy',  className: 'btn btn-sm btn-secondary' },
      { extend: 'excel', className: 'btn btn-sm btn-success',  text: '<i class="bi bi-file-earmark-excel me-1"></i>Excel' },
      { extend: 'csv',   className: 'btn btn-sm btn-info',     text: '<i class="bi bi-filetype-csv me-1"></i>CSV' },
      { extend: 'pdf',   className: 'btn btn-sm btn-danger',   text: '<i class="bi bi-file-earmark-pdf me-1"></i>PDF' },
      { extend: 'print', className: 'btn btn-sm btn-secondary' },
    ],
    language: {
      search: 'Global search:',
      lengthMenu: 'Show _MENU_ entries',
      info: 'Showing _START_ to _END_ of _TOTAL_ Vehicle Model records',
    },
  });

  $('#vehicleModelSearchTable tbody').on('click', 'tr', function () {
    const data = table.row(this).data();
    if (!data) return;
    bootstrap.Modal.getInstance(document.getElementById('vehicleModelSearchModal')).hide();
    document.dispatchEvent(new CustomEvent('vehicle_model-selected', { detail: data }));
  });

  $('#vehicleModelSearchModal').on('shown.bs.modal', function () {
    table.ajax.reload(null, false);
    table.columns.adjust();
  });

});