<?php /* modules/master_files/vehicle/vehicle_model/vehicle_model.php — generated by Generate Module */ ?>

<div id="vehicle-model-app" class="row g-4">
  <div class="col-12">
    <div class="card card-primary card-outline mb-4">
      <div class="card-header"><div class="card-title">{{ title }}</div></div>
      <div class="card-body">

        <div class="d-flex flex-wrap gap-2 mb-4">
          <div class="btn-group" role="group">
            <button type="button" class="btn btn-primary" @click="onAdd">New</button>
            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#vehicleModelSearchModal">Search</button>
            <button type="button" class="btn btn-info" @click="onPrint">Print</button>
            <button type="button" class="btn btn-warning" @click="onCancel">Cancel</button>
            <button type="button" class="btn btn-danger" @click="onClose">Close</button>
          </div>
          <button type="button" class="btn btn-outline-secondary btn-sm ms-auto module-help-btn" title="Help">
            <i class="bi bi-question-circle me-1"></i>Help
          </button>
        </div>

        <div class="row mt-2 g-4">
          <div class="col-md-6">
            <div class="row mb-3">
              <label for="vehicle-model-ref" class="col-sm-4 col-form-label">Reference No.</label>
              <div class="col-sm-8">
                <div class="input-group">
                  <input type="text" class="form-control font-monospace" id="vehicle-model-ref" v-model="form.ref" disabled />
                  <span v-if="loading" class="input-group-text"><span class="spinner-border spinner-border-sm"></span></span>
                </div>
              </div>
            </div>
            <div class="row mb-3">
      <label for="vehicle-model-code" class="col-sm-4 col-form-label">Code</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-model-code" v-model="form.code" required />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-model-name" class="col-sm-4 col-form-label">Model Name</label>
      <div class="col-sm-8">
        <input type="text" class="form-control" id="vehicle-model-model-name" v-model="form.model_name" required />
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Brand</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-model-brand-ref" v-model="form.brand_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.brand_name" placeholder="Brand…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vmBrandPickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearBrand" v-if="form.brand_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Vehicle Type</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-model-vehicle-type-ref" v-model="form.vehicle_type_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.vehicle_type_name" placeholder="Vehicle type…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vmVehicleTypePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearVehicleType" v-if="form.vehicle_type_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label class="col-sm-4 col-form-label">Fuel Type</label>
      <div class="col-sm-8">
        <div class="input-group">
          <input type="text" class="form-control font-monospace" id="vehicle-model-fuel-type-ref" v-model="form.fuel_type_ref" placeholder="Ref…" readonly style="max-width:150px" />
          <input type="text" class="form-control" v-model="form.fuel_type_name" placeholder="Fuel type…" readonly />
          <button class="btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#vmFuelTypePickerModal">
            <i class="bi bi-search"></i>
          </button>
          <button class="btn btn-outline-secondary" type="button" @click="clearFuelType" v-if="form.fuel_type_ref">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-manufacture-start-year" class="col-sm-4 col-form-label">Manufacture Start Year</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="vehicle-model-manufacture-start-year" v-model.number="form.manufacture_start_year" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-manufacture-end-year" class="col-sm-4 col-form-label">Manufacture End Year</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="vehicle-model-manufacture-end-year" v-model.number="form.manufacture_end_year" />
      </div>
    </div>
          </div>
          <div class="col-md-6">
    <div class="row mb-3">
      <label for="vehicle-model-axle-count" class="col-sm-4 col-form-label">Axle Count</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="vehicle-model-axle-count" v-model.number="form.axle_count" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-seating-capacity" class="col-sm-4 col-form-label">Seating Capacity</label>
      <div class="col-sm-8">
        <input type="number" step="1" class="form-control" id="vehicle-model-seating-capacity" v-model.number="form.seating_capacity" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-payload-capacity-kg" class="col-sm-4 col-form-label">Payload Capacity (kg)</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="vehicle-model-payload-capacity-kg" v-model.number="form.payload_capacity_kg" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-volume-capacity-m3" class="col-sm-4 col-form-label">Volume Capacity (m3)</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="vehicle-model-volume-capacity-m3" v-model.number="form.volume_capacity_m3" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-fuel-tank-capacity-l" class="col-sm-4 col-form-label">Fuel Tank Capacity (L)</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="vehicle-model-fuel-tank-capacity-l" v-model.number="form.fuel_tank_capacity_l" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-average-fuel-consumption" class="col-sm-4 col-form-label">Average Fuel Consumption</label>
      <div class="col-sm-8">
        <input type="number" step="0.01" class="form-control" id="vehicle-model-average-fuel-consumption" v-model.number="form.average_fuel_consumption" />
      </div>
    </div>
    <div class="row mb-3">
      <label for="vehicle-model-description" class="col-sm-4 col-form-label">Description</label>
      <div class="col-sm-8">
        <textarea class="form-control" id="vehicle-model-description" v-model="form.description"></textarea>
      </div>
    </div>
          </div>
        </div>

      </div>
      <div class="card-footer d-flex align-items-center">
        <span class="text-danger small" v-if="error">{{ error }}</span>
        <span class="text-success small" v-if="saved">Vehicle Model saved successfully.</span>
        <button type="button" class="btn btn-success btn-lg px-5 ms-auto" @click="onSave" :disabled="!isDirty || saving">
          <span v-if="saving" class="spinner-border spinner-border-sm me-2" role="status"></span>
          <i v-else class="bi bi-check-lg me-2"></i>Save
        </button>
      </div>
    </div>
  </div>
</div>

<?php include __DIR__ . '/vehicle_model_search.php'; ?>
<script>const SYSTEM_NAME = '<?= htmlspecialchars($page) ?>';</script>
<script src="/modules/master_files/vehicle/vehicle_model/vehicle_model.js"></script>