<?php
// vehicle_model_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveVehicleModel(array $data): array {
    $ref = consumeNextReference('vehicle_model');

    return supabase_post(SB_API . 'm_vehicle_models', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'model_name' => $data['model_name'] ?? '',
        'brand_ref' => !empty($data['brand_ref']) ? $data['brand_ref'] : null,
        'vehicle_type_ref' => !empty($data['vehicle_type_ref']) ? $data['vehicle_type_ref'] : null,
        'fuel_type_ref' => !empty($data['fuel_type_ref']) ? $data['fuel_type_ref'] : null,
        'manufacture_start_year' => $data['manufacture_start_year'] ?? 0,
        'manufacture_end_year' => $data['manufacture_end_year'] ?? 0,
        'axle_count' => $data['axle_count'] ?? 0,
        'seating_capacity' => $data['seating_capacity'] ?? 0,
        'payload_capacity_kg' => $data['payload_capacity_kg'] ?? 0,
        'volume_capacity_m3' => $data['volume_capacity_m3'] ?? 0,
        'fuel_tank_capacity_l' => $data['fuel_tank_capacity_l'] ?? 0,
        'average_fuel_consumption' => $data['average_fuel_consumption'] ?? 0,
        'description' => $data['description'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateVehicleModel(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_vehicle_models', $ref)) {
        return ['error' => 'Record not found.'];
    }

    return supabase_patch(SB_API . 'm_vehicle_models?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'model_name' => $data['model_name'] ?? '',
        'brand_ref' => !empty($data['brand_ref']) ? $data['brand_ref'] : null,
        'vehicle_type_ref' => !empty($data['vehicle_type_ref']) ? $data['vehicle_type_ref'] : null,
        'fuel_type_ref' => !empty($data['fuel_type_ref']) ? $data['fuel_type_ref'] : null,
        'manufacture_start_year' => $data['manufacture_start_year'] ?? 0,
        'manufacture_end_year' => $data['manufacture_end_year'] ?? 0,
        'axle_count' => $data['axle_count'] ?? 0,
        'seating_capacity' => $data['seating_capacity'] ?? 0,
        'payload_capacity_kg' => $data['payload_capacity_kg'] ?? 0,
        'volume_capacity_m3' => $data['volume_capacity_m3'] ?? 0,
        'fuel_tank_capacity_l' => $data['fuel_tank_capacity_l'] ?? 0,
        'average_fuel_consumption' => $data['average_fuel_consumption'] ?? 0,
        'description' => $data['description'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listVehicleModel(): array {
    return supabase_get(SB_API . 'm_vehicle_models?select=id,ref,code,model_name,brand_ref,vehicle_type_ref,fuel_type_ref,manufacture_start_year,manufacture_end_year,axle_count,seating_capacity,payload_capacity_kg,volume_capacity_m3,fuel_tank_capacity_l,average_fuel_consumption,description,m_vehicle_brands(name),m_vehicle_types(name),m_fuel_types(name)&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listVehicleModel());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveVehicleModel($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateVehicleModel($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_vehicle_models', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}