// vehicle_model.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      code: '',
      model_name: '',
      brand_ref: '',
      brand_name: '',
      vehicle_type_ref: '',
      vehicle_type_name: '',
      fuel_type_ref: '',
      fuel_type_name: '',
      manufacture_start_year: 0,
      manufacture_end_year: 0,
      axle_count: 0,
      seating_capacity: 0,
      payload_capacity_kg: 0,
      volume_capacity_m3: 0,
      fuel_tank_capacity_l: 0,
      average_fuel_consumption: 0,
      description: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.code !== '' ||
        this.form.model_name !== '' ||
        this.form.brand_ref !== '' ||
        this.form.vehicle_type_ref !== '' ||
        this.form.fuel_type_ref !== '' ||
        this.form.manufacture_start_year !== 0 ||
        this.form.manufacture_end_year !== 0 ||
        this.form.axle_count !== 0 ||
        this.form.seating_capacity !== 0 ||
        this.form.payload_capacity_kg !== 0 ||
        this.form.volume_capacity_m3 !== 0 ||
        this.form.fuel_tank_capacity_l !== 0 ||
        this.form.average_fuel_consumption !== 0 ||
        this.form.description !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('vehicle_model-selected', (e) => this.loadRecord(e.detail));
    document.addEventListener('vm-brand-selected', (e) => {
      this.form.brand_ref  = e.detail.ref;
      this.form.brand_name = e.detail.name;
    });
    document.addEventListener('vm-vehicle-type-selected', (e) => {
      this.form.vehicle_type_ref  = e.detail.ref;
      this.form.vehicle_type_name = e.detail.name;
    });
    document.addEventListener('vm-fuel-type-selected', (e) => {
      this.form.fuel_type_ref  = e.detail.ref;
      this.form.fuel_type_name = e.detail.name;
    });
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    clearBrand()       { this.form.brand_ref = '';        this.form.brand_name = ''; },
    clearVehicleType() { this.form.vehicle_type_ref = '';  this.form.vehicle_type_name = ''; },
    clearFuelType()    { this.form.fuel_type_ref = '';     this.form.fuel_type_name = ''; },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/vehicle/vehicle_model/vehicle_model_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        code: String(this.form.code ?? ''),
        model_name: String(this.form.model_name ?? ''),
        brand_name: String(this.form.brand_name ?? ''),
        vehicle_type_name: String(this.form.vehicle_type_name ?? ''),
        fuel_type_name: String(this.form.fuel_type_name ?? ''),
        manufacture_start_year: String(this.form.manufacture_start_year ?? ''),
        manufacture_end_year: String(this.form.manufacture_end_year ?? ''),
        axle_count: String(this.form.axle_count ?? ''),
        seating_capacity: String(this.form.seating_capacity ?? ''),
        payload_capacity_kg: String(this.form.payload_capacity_kg ?? ''),
        volume_capacity_m3: String(this.form.volume_capacity_m3 ?? ''),
        fuel_tank_capacity_l: String(this.form.fuel_tank_capacity_l ?? ''),
        average_fuel_consumption: String(this.form.average_fuel_consumption ?? ''),
        description: String(this.form.description ?? ''),
          });
          window.open('/modules/master_files/vehicle/vehicle_model/vehicle_model_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.code = '';
      this.form.model_name = '';
      this.form.brand_ref = '';
      this.form.brand_name = '';
      this.form.vehicle_type_ref = '';
      this.form.vehicle_type_name = '';
      this.form.fuel_type_ref = '';
      this.form.fuel_type_name = '';
      this.form.manufacture_start_year = 0;
      this.form.manufacture_end_year = 0;
      this.form.axle_count = 0;
      this.form.seating_capacity = 0;
      this.form.payload_capacity_kg = 0;
      this.form.volume_capacity_m3 = 0;
      this.form.fuel_tank_capacity_l = 0;
      this.form.average_fuel_consumption = 0;
      this.form.description = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/vehicle/vehicle_model/vehicle_model_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/vehicle/vehicle_model/vehicle_model_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.code = data.code;
      this.form.model_name = data.model_name;
      this.form.brand_ref = data.brand_ref ?? '';
      this.form.brand_name = data.m_vehicle_brands?.name ?? '';
      this.form.vehicle_type_ref = data.vehicle_type_ref ?? '';
      this.form.vehicle_type_name = data.m_vehicle_types?.name ?? '';
      this.form.fuel_type_ref = data.fuel_type_ref ?? '';
      this.form.fuel_type_name = data.m_fuel_types?.name ?? '';
      this.form.manufacture_start_year = data.manufacture_start_year;
      this.form.manufacture_end_year = data.manufacture_end_year;
      this.form.axle_count = data.axle_count;
      this.form.seating_capacity = data.seating_capacity;
      this.form.payload_capacity_kg = data.payload_capacity_kg;
      this.form.volume_capacity_m3 = data.volume_capacity_m3;
      this.form.fuel_tank_capacity_l = data.fuel_tank_capacity_l;
      this.form.average_fuel_consumption = data.average_fuel_consumption;
      this.form.description = data.description;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#vehicle-model-app');