// employee_master.js — generated by Generate Module

const { createApp } = Vue;

createApp({
  data() {
    return {
      systemName: SYSTEM_NAME,
      title:      '',
      loading: false,
      saving:  false,
      saved:   false,
      error:   '',
      isExisting: false,
      form: {
        ref: '',
      code: '',
      full_name: '',
      date_of_birth: '',
      phone: '',
      mobile: '',
      email: '',
      address: '',
      bank_name: '',
      bank_branch: '',
      bank_account_number: '',
      tax_number: '',
      remarks: '',
      },
    };
  },

  computed: {
    isDirty() {
      return (
        this.form.code !== '' ||
        this.form.full_name !== '' ||
        this.form.date_of_birth !== '' ||
        this.form.phone !== '' ||
        this.form.mobile !== '' ||
        this.form.email !== '' ||
        this.form.address !== '' ||
        this.form.bank_name !== '' ||
        this.form.bank_branch !== '' ||
        this.form.bank_account_number !== '' ||
        this.form.tax_number !== '' ||
        this.form.remarks !== ''
      );
    },
  },

  mounted() {
    this.fetchRefNumber();
    document.addEventListener('employee_master-selected', (e) => this.loadRecord(e.detail));
  },

  methods: {
    fetchRefNumber() {
      this.loading = true;
      axios.get('/server/general/module_data.php?system_name=' + this.systemName)
        .then(res => { this.form.ref = res.data.ref; this.title = res.data.module; })
        .catch(err => { this.error = 'Failed to load reference number.'; console.error(err); })
        .finally(() => { this.loading = false; });
    },

    onAdd()    { this.onReset(); this.fetchRefNumber(); },
    onPrint() {
      if (!this.form.ref) { this.error = 'No record to print. Search and select a saved record first.'; return; }
      axios.get('/modules/master_files/people/employee_master/employee_master_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
        .then(res => {
          if (!res.data.exists) {
            this.error = 'No saved record found for this reference. Please search and select a record to print.';
            return;
          }
          const params = new URLSearchParams({
            ref: this.form.ref,
        code: String(this.form.code ?? ''),
        full_name: String(this.form.full_name ?? ''),
        date_of_birth: String(this.form.date_of_birth ?? ''),
        phone: String(this.form.phone ?? ''),
        mobile: String(this.form.mobile ?? ''),
        email: String(this.form.email ?? ''),
        address: String(this.form.address ?? ''),
        bank_name: String(this.form.bank_name ?? ''),
        bank_branch: String(this.form.bank_branch ?? ''),
        bank_account_number: String(this.form.bank_account_number ?? ''),
        tax_number: String(this.form.tax_number ?? ''),
        remarks: String(this.form.remarks ?? ''),
          });
          window.open('/modules/master_files/people/employee_master/employee_master_print.php?' + params.toString(), '_blank');
        })
        .catch(err => { this.error = 'Failed to verify record.'; console.error(err); });
    },
    onCancel() { this.onReset(); },
    onClose()  { this.onReset(); },

    onReset() {
      this.saved = false;
      this.error = '';
      this.isExisting = false;
      this.form.code = '';
      this.form.full_name = '';
      this.form.date_of_birth = '';
      this.form.phone = '';
      this.form.mobile = '';
      this.form.email = '';
      this.form.address = '';
      this.form.bank_name = '';
      this.form.bank_branch = '';
      this.form.bank_account_number = '';
      this.form.tax_number = '';
      this.form.remarks = '';
    },

    onSave() {
      if (!this.isDirty) return;
      this.saving = true;
      this.saved  = false;
      this.error  = '';

      const proceed = (action) => {
        axios.post('/modules/master_files/people/employee_master/employee_master_data.php?action=' + action, this.form)
          .then(() => {
            this.saved = true;
            this.onReset();
            this.fetchRefNumber();
          })
          .catch(err => { this.error = 'Failed to save.'; console.error(err); })
          .finally(() => { this.saving = false; });
      };

      if (this.isExisting) {
        axios.get('/modules/master_files/people/employee_master/employee_master_data.php?action=exists&ref=' + encodeURIComponent(this.form.ref))
          .then(res => {
            if (!res.data.exists) { this.error = 'Record not found. Please search again.'; this.saving = false; return; }
            proceed('update');
          })
          .catch(err => { this.error = 'Failed to verify record.'; console.error(err); this.saving = false; });
      } else {
        proceed('save');
      }
    },

    loadRecord(data) {
      this.form.ref = data.ref;
      this.form.code = data.code;
      this.form.full_name = data.full_name;
      this.form.date_of_birth = data.date_of_birth;
      this.form.phone = data.phone;
      this.form.mobile = data.mobile;
      this.form.email = data.email;
      this.form.address = data.address;
      this.form.bank_name = data.bank_name;
      this.form.bank_branch = data.bank_branch;
      this.form.bank_account_number = data.bank_account_number;
      this.form.tax_number = data.tax_number;
      this.form.remarks = data.remarks;
      this.isExisting = true;
      this.saved = false;
      this.error = '';
    },
  },
}).mount('#employee-master-app');