<?php
// employee_master_data.php — generated by Generate Module

require_once __DIR__ . '/../../../../server/supabase.php';
require_once __DIR__ . '/../../../../server/session.php';
require_once __DIR__ . '/../../../../server/general/number_series.php';

header('Content-Type: application/json');

function saveEmployeeMaster(array $data): array {
    $code = trim($data['code'] ?? '');
    $existing = supabase_get(SB_API . 'm_employees?select=id&code=eq.' . urlencode($code) . '&limit=1');
    if (!empty($existing)) {
        http_response_code(409);
        return ['error' => "Code '{$code}' already exists."];
    }

    $ref = consumeNextReference('employee_master');

    return supabase_post(SB_API . 'm_employees', [
        'ref' => $ref,
        'code' => $data['code'] ?? '',
        'full_name' => $data['full_name'] ?? '',
        'date_of_birth' => !empty($data['date_of_birth']) ? $data['date_of_birth'] : null,
        'phone' => $data['phone'] ?? '',
        'mobile' => $data['mobile'] ?? '',
        'email' => $data['email'] ?? '',
        'address' => $data['address'] ?? '',
        'bank_name' => $data['bank_name'] ?? '',
        'bank_branch' => $data['bank_branch'] ?? '',
        'bank_account_number' => $data['bank_account_number'] ?? '',
        'tax_number' => $data['tax_number'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'created_by' => current_user()['ref'] ?? null,
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function updateEmployeeMaster(array $data): array {
    $ref = trim($data['ref'] ?? '');
    if ($ref === '' || !recordExists('m_employees', $ref)) {
        return ['error' => 'Record not found.'];
    }

    $code = trim($data['code'] ?? '');
    $dup = supabase_get(SB_API . 'm_employees?select=id&code=eq.' . urlencode($code) . '&ref=neq.' . urlencode($ref) . '&limit=1');
    if (!empty($dup)) {
        http_response_code(409);
        return ['error' => "Code '{$code}' already exists."];
    }

    return supabase_patch(SB_API . 'm_employees?ref=eq.' . urlencode($ref), [
        'code' => $data['code'] ?? '',
        'full_name' => $data['full_name'] ?? '',
        'date_of_birth' => !empty($data['date_of_birth']) ? $data['date_of_birth'] : null,
        'phone' => $data['phone'] ?? '',
        'mobile' => $data['mobile'] ?? '',
        'email' => $data['email'] ?? '',
        'address' => $data['address'] ?? '',
        'bank_name' => $data['bank_name'] ?? '',
        'bank_branch' => $data['bank_branch'] ?? '',
        'bank_account_number' => $data['bank_account_number'] ?? '',
        'tax_number' => $data['tax_number'] ?? '',
        'remarks' => $data['remarks'] ?? '',
        'updated_by' => current_user()['ref'] ?? null,
    ]);
}

function listEmployeeMaster(): array {
    return supabase_get(SB_API . 'm_employees?select=id,ref,code,full_name,date_of_birth,phone,mobile,email,address,bank_name,bank_branch,bank_account_number,tax_number,remarks&order=id.asc');
}

$action = $_GET['action'] ?? '';

if ($action === 'list') {
    echo json_encode(listEmployeeMaster());

} elseif ($action === 'save') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(saveEmployeeMaster($body));

} elseif ($action === 'update') {
    $body = json_decode(file_get_contents('php://input'), true) ?? [];
    echo json_encode(updateEmployeeMaster($body));

} elseif ($action === 'exists') {
    $ref = $_GET['ref'] ?? '';
    echo json_encode(['exists' => $ref !== '' && recordExists('m_employees', $ref)]);

} else {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid action']);
}